### ISSUE TITLE
Not possible to upload data

### ISSUE THREAD

**Issue by JanisKuegler** [ls1intum/Artemis#1094]
### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by JanisKuegler** [comment]
I uploaded my file in Artemis at 0:10 on Monday, but Artemis had I problem. I tried for 30 min, but Artemis didn't work. When I checked my results this morning it says build failed.

**Comment by jpbernius** [comment]
Hello @JanisKuegler, thanks for reporting a problem here.

Unfortunately, we cannot assist you with your problem due to missing informations.
If you are facing a concrete bug with the Artemis system, please fill our the template and provide detailed information on the problem and how to reproduce it.

For questions regarding the operation of our Artemis instance, this is **not** the right channel. Please contact the instructor of your course.
