### ISSUE TITLE
Some assessments cannot be overriden and feature requests for file upload workflow

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [ls1intum/Artemis#1117]
### Describe the bug
Our current workflow is to grade submissions that could not be opened by tutors because of special characters in the filename and therefore got 0 points. We therefore identified problematic submissions and are manually re-reviewing them by overriding the last feedback. This workflow leads to several problems:

Some assessments have "greyed out" buttons and so regardless of the change in the Feedback, it cannot be submitted.
**-> Please let us override any assessment _(bug)_ and/or let us remove the lock _(feature request)_ so that the submission can be reassigned.**

As Tutors cannot override assessments, but Instructors, we had to grant a Tutor Instructor privileges. It would be useful if Tutors also had the possibility to override assessments, so one could just message the tutors with the file or a hint e.g. to regrade the submission using Firefox. For the programming exercises this works very neatly with "new result".
**-> Please give Tutors the privilege to override assessments _(feature request)_**

As one only sees the first name of the Tutor that has a lock this can lead to confusion as some Tutors share the same first name.
**-> Please show the first and last name of the tutor and/or their LRZ ID _(feature request)_**

#### To Reproduce
Example assesments that cannot be overridden: 
https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/460189/assessment
https://artemis.ase.in.tum.de/#/file-upload-exercise/769/submission/414483/assessment

Example assesment that works like expected: https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/443186/assessment

#### Expected behavior
![Снимок экрана 2019-12-04 в 4 06 59](https://user-images.githubusercontent.com/20713070/70109277-b861d900-164b-11ea-8d6f-e70e86ce2692.png)

#### Unexpected behavior
![Снимок экрана 2019-12-04 в 4 06 54](https://user-images.githubusercontent.com/20713070/70109285-c0217d80-164b-11ea-846a-8936fe61ddb0.png)
Update: Spoke with the Tutor and was told, that his pc crashed and he could not find the assessment anymore in his list of assessments (even though he can't say for sure it was this submission, but could be a starting point), so he thought another Tutor was assessed it.

**Comment by krusche** [comment]
Some additional explanation about our intended implementation:

1) Tutors who have the lock can cancel their assessment and release the lock. They can override their own assessment until the assessment due date (if it was set). Tutors can only lock at most 10 submissions at the same time in the whole course without submitting the assessment.

2) It is by design that tutors cannot simply override assessments by other tutors as this could lead to a lot of problems when it comes to complaints.

3) Instructors can always override tutor assessments

I improved that the lock is now displayed with the full name + login.

It is currently not possible that instructors remove the lock from an assessment, but we can implement this in the future. I opened a new issue for this: https://github.com/ls1intum/Artemis/issues/1150
