### ISSUE TITLE
Ability to add assessments for e-mailed participations

### ISSUE THREAD

**Issue by jerhard** [ls1intum/Artemis#1121]
### Is your feature request related to a problem?
When facing downtimes or other technical issues with Artemis, students might provide their submissions via e-mail to the instructors to meet submission deadlines.
To provide instructors, tutors and students with a single infrastructure to deal with assessments,
there should be a way to store assessments for these e-mail participations in Artemis. 
Currently, there is no way to store assessments for students for non-programming exercises for which they have not made a submission on Artemis, and for programming exercises where they did not click  "start exercise" on Artemis.

### Describe the solution you'd like
Tutors should be able to enter assessments for course-participants that did not submit their exercise via Artemis (but via e-mail). 
These assessments should be identifiable as such afterwards compared to normal assessments, 
as this would allow to keep track of which of the e-mailed submissions were already  assessed and to make sure that no extra assessments are made.

### Additional context
It might be subject to debate which group of users should be granted this ability, i.e. whether just to instructors or both to instructors and tutors. The workflow might only involve only a few people providing assessments for e-mailed submissions, so that a restriction of this ability to instructors might still be feasible in practice.

A possible implementation might be to give instructors the ability to import student submissions (code/files/text) into Artemis, so that they can be graded by tutors.

**Comment by krusche** [comment]
As discussed via email:

In a first step, instructors (or tutors) can add new results with an "empty" submission independent of an exercise.

After navigating into the exercise details (click on View), there should be a new button for this action. Then the instructor needs to choose a student using a text field and search (comparable to the one used on the scores page). After selecting the student, the instructor can add the following details:
- result text
- result score
- feedback elements (here we can reuse how feedback is generated in the assessment dialogs)
- decide if the result is rated or unrated (default is rated)

In case the student did not start the exercise yet, a new participation needs to be generated. The initializationDate should be set to the current date (on the server), the initializationState should be set to FINISHED immediately. No other values (e.g. repo, build plan, etc.) are set for the participation.
The result and the submission date are set to the current date (on the server).
The submission is flagged as submitted. The submission type is set to EXTERNAL (new enum value). Depending on the exercise type, the corresponding concrete submission needs to be created.
Result, submission and participation need to be connected properly.
In the first step, the instructor cannot add the submission content (e.g. file, text, model, code), so we keep the submission "empty".
In addition, this action should be inserted into the audit log, so that we can track such actions easily in the future. 


In a second step, we should allow the instructor to add the actual submission of the student (e.g. the file, the text, the model, the code). In case of text and file upload exercises, this should be easy. However for models and code, this could be more difficult, because additional actions (import the model using json, import the code using a zip file) would be necessary that would also need checks if the structure is correct.
