### ISSUE TITLE
Order of assessment elements in Apollon wrong

### ISSUE THREAD

**Issue by Kn3cht** [ls1intum/Artemis#1342]
### Description
When double clicking a class sometimes attributes (most of the time the second item) are not part of the class correction pop-up:

#### To Reproduce
1. Open the grading of an AOM
2. Double click on a not-automatically graded class
3. Check if all attributes are listed

#### Screenshots
![image](https://user-images.githubusercontent.com/18322652/80186939-18fbad80-860f-11ea-87de-c693de17b566.png)

**Comment by krusche** [comment]
I think the order is wrong, if you scroll down, you should see it.

@TobiasPr can you please double check why the order of the assessments in this dialog is not like the order of attributes and methods in the class?

**Comment by Kn3cht** [comment]
@krusche thanks for the fast reply, I double checked the submission and indeed only the order was wrong!

**Comment by krusche** [comment]
Let's rename the issue and not close it, because it is a problem that should be fixed

**Comment by TobiasPr** [comment]
I will look into that - the issue seems to be that methods and attributes are represented in the order in which they were added, but I will fix that

**Comment by TobiasPr** [comment]
Okay after looking into this issue in more detail, I think that this requires a bigger change because its not easily implementable because of some design decisions of the current architecture. How the assessment popup is displayed is currently decoupled of the concrete elements it displays. It simply takes all the elements in the assessment element hierarchy and generates an assessment section for each element. This hierarchy is ordered based on the order in which the elements where inserted (new elements are simply appended). 
I came up with two solutions in the current architecture which I do not like, but for the sake of discussing them I will explain them shortly:

Relevant architecture decisions, which lead to this "problem":

- Containers do not know their elements, they have a list of references [ownedElements] which can be used together with the global state to identify which elements they actually contain
- Insertion of elements into a container is handled generically for all containers

1. Don't change anything in the way elements are inserted into the container, give the containers a new function getOrderedElements(children: IUMLElement[]) in which the container gets its own children as parameter and orders them -> IMO that's really bad design

2. Change the ownedElements: reference to a sorted list of references. Therefore the responsibility of inserting an element into an container must be given to container and delegated from the generic function, the function would look like insert(newElement: IUMLElement, currentChildren: IUMLElement[]) -> same problem, the container has no way of getting the extra information about its elements (it just have the list of children ids)

My suggestion: change the architecture in a way, that each element has full information on its children and each child has full information on its parent. This would lead to redundant information in the model state. On the one hand the diagram knows all its elements and the elements themselves know all their children (and recursively the full tree / all elements). So I suggest removing the elements from the model state and replacing them by this tree like hierarchical structure in which each element knows only its children and its parent. I need to still look a bit further in potential drawbacks or if it will stop some features we are currently having from working properly

**Comment by krusche** [comment]
@TobiasPr I suggest we find a workaround / easy solution for now to fix the problem and discuss architecture changes later. Can we at least make sure that the order of

Class
Attributes
Methods

is correct, so that methods cannot be shown before attributes in this dialog?

Apart from that, I think the dialog which shows the whole "container" element, needs to have a reference to this "container" element, so that it can access all childrens. Then, the dialog can sort the assessments in the same order as the children of the "container element". Would this be possible?
