### ISSUE TITLE
SSH clone

### ISSUE THREAD

**Issue by tobiasmoldan** [ls1intum/Artemis#1371]
### Is your feature request related to a problem?
After starting a coding exercise it would be nice if we could get the ssh url to clone our project, so that we don't have to go to bitbucket every time or always enter our password.

### Describe the solution you'd like
See github clone button

### Describe alternatives you've considered
If merging it in the current clone element is too expensive then maybe adding another element.

**Comment by krusche** [comment]
We could display a dropdown menu with https and ssh left to the URL. Default would be https and students could change it to ssh. This could also be saved in the browser's local storage so that students don't need to change this all the time.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/744067/80911016-e307a900-8d33-11ea-8d2a-280184b5f303.png">


Another possibility would be to have a "use ssh" button in the upper right corner like in Github.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/744067/80910998-bc497280-8d33-11ea-889e-509cf95c374d.png">

I like that they display a warning when choosing ssh, I think we should also do that because the majority of students won't have setup a public ssh key.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/744067/80910988-b0f64700-8d33-11ea-8386-66b8df501878.png">

**Comment by just-max** [comment]
Any chance that Artemis could remember the choice of SSH/HTTPS? It's not a big deal but its a nice usability improvement if the right URL is always there.

Also in the message "To use ssh, you need to add an ssh-key to your account here." I feel like SSH should be capitalized, since it is an acronym (and usually capitalized, see for example https://en.wikipedia.org/wiki/Secure_Shell)

Also visually the "USE HTTPS"/"USE SSH" text looks really big, I feel like "Use HTTPS"/"Use SSH" is nicer visually.

Those last two points are obviously rather unimportant but the first one would be a nice improvement.
