### ISSUE TITLE
Change SGI UI Component in Modeling Exercise Editor

### ISSUE THREAD

**Issue by TobiasPr** [ls1intum/Artemis#1396]
### Is your feature request related to a problem?

Currently its confusing to users that an Exercise can have Grading instructions + Structured Grading instructions. Visually how we present this feature is like this:
![image](https://user-images.githubusercontent.com/22955066/81055842-d0bf7380-8ec9-11ea-8d08-0845b6ed7ad2.png)

The toggle indicates an "either or" feature. I would suggest to change it to some other control in order to make it more clear to the user that its not an either or feature. My suggestion would be a tab view or adding a separate editor for SGIs

**Comment by HanyaElhashemy** [comment]
I tried out both suggestions and unfortunately tab view was not intuitive as well since there is another tab view right beneath and the UI design looked a bit off imo
![image](https://user-images.githubusercontent.com/50635005/82131557-ada09800-97d6-11ea-8ddc-7f6aa5f24f58.png)
So I went for your 2nd suggestion which is adding a separate editor in PR #1483 . Let me know what you think @TobiasPr @krusche
