### ISSUE TITLE
Notes functionality or "star" functionality for assessments

### ISSUE THREAD

**Issue by Kn3cht** [ls1intum/Artemis#1402]
### Double checking
During the correction period grading criteria might change or be newly defined. During the correction a tutor might notice some undefined cases which he might need to change afterwards without going through all assessments.

### Solution
I know that the "lock" feature kind of solves this problem but nevertheless it might be helpful as a tutor to mark assessments with notes or with the proven concept of "staring" them. 

### Alternative
A good alternative to the notes section (it could get quite messy with all different kinds of notes during the correction) would be a sneak peak view on the assessment in the list (e.g. wikipedia when hovering over a link).

**Comment by chrisknedl** [comment]
Just a comment on how I am planning to do this:
I think it would make sense to split this into two PRs. 

The first one adds the functionality, which in this case means to add a textbox in the manual assessment view. A fitting place would maybe be just below the `Feedback` headline. The text itself is added as a String to the `Result` DomainObject and also in the Client code. That concludes PR 1.

PR Nr. 2 then adds a little icon to the submissions overview, so that tutors can easily identify the assessments that need to be revisited. When hovering over the icon with the mouse, a small preview of the note is shown (or the whole thing, depending on the length of the tutor note).
