### ISSUE TITLE
Activity, Use Case, Component and Deployment Diagrams: child elements disappear when dragged into container

### ISSUE THREAD

**Issue by tobiasschamel** [ls1intum/Artemis#1417]
### Describe the bug
When using the model editor of H02E01, Use Case ellipses become hidden if dragged & dropped onto a System frame element.

#### To Reproduce

1. Start model editor (functional) of H02E01
2. Add system frame (via drag & drop)
3. Drag & drop a use case ellipse onto system frame
4. See error (use case disappears)

#### Expected behavior
Use Case ellipse is bound to the system element as on apollon.ase.in.tum.de

#### Screenshots

![weird](https://user-images.githubusercontent.com/58089908/81148475-a084dd00-8f7c-11ea-810c-337fb992860e.PNG)

### Environment
On different OS' & browsers.
<details><pre>
 - MacOs Catalina 10.15.4 (19E287): Safari Version 13.1 (15609.1.20.111.8)
 - MacOs Catalina 10.15.4 (19E287): Chrome Version 81.0.4044.129
 - Ubuntu 18.04.3 (Rechnerhalle): Firefox 72.0.1
 - Ubuntu 18.04.3 (Rechnerhalle): Chromium 79.0.3945.79
 - Windows: Chrome & Firefox (no details)
</pre></details>

**Comment by reuta** [comment]
A lot of people including me have the same issue. But interestingly i found out that the issue only arises on artemis itself. If you try it on https://apollon.ase.in.tum.de/ it works perfectly fine without any problems.

**Comment by krusche** [comment]
@TobiasPr could you please have a look at this issue? I guess we need to make sure that a container (e.g. system boundaries in use case diagrams or packages in Class diagrams) is always shown in the background of its child elements.

Would be great if we could fix this bug quickly so that the students can model without problems. Thanks!

**Comment by TobiasPr** [comment]
This bug is affecting `Activity Diagrams`, `Use Case Diagrams`, `Component Diagrams` and `Deployment Diagrams`

We implemented a fix for this and its currently deployed on the test environment. Feel free to test it: https://artemistest.ase.in.tum.de/#/courses/114/exercises/1884

@reuta that's the case, because the newest updates of Apollon did not include anything for the standalone version, so we did not update https://apollon.ase.in.tum.de with the newest version

@tobiasschamel @reuta thanks for the notification, we will deploy the fix this evening
