### ISSUE TITLE
Layer System for after packaging and systemframe  deploy

### ISSUE THREAD

**Issue by nico-hoff** [ls1intum/Artemis#1432]
#### To Reproduce

1. Put a Package element after deploying a class object and due to no layers, the package element always stays in front of the other object.

#### Expected behavior
Button: "to Background"

#### Screenshots
<img width="521" alt="image" src="https://user-images.githubusercontent.com/43175972/81332553-8db8f800-90a3-11ea-95ce-ab4f84332084.png">

### Environment

  Modellname:	MacBook Pro
  Modell-Identifizierung:	MacBookPro14,1
  Prozessortyp:	Dual-Core Intel Core i5
  Prozessorgeschwindigkeit:	2,3 GHz
  Anzahl der Prozessoren:	1
  Gesamtanzahl der Kerne:	2
  L2-Cache (pro Kern):	256 KB
  L3-Cache:	4 MB
  Hyper-Threading Technologie:	Aktiviert
  Speicher:	8 GB

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
Should be fixed with the newest release 4.0.5

Please test it again. In case you add the package after the classes, you cannot move the package above the classes. You need to select the classes (using Shift you can select multiple elements) and move them on top of the package, then the elements will be reordered so that child elements will be shown on top of container elements.
