### ISSUE TITLE
Quiz answers being set to invalid leading to incorrect evaluation

### ISSUE THREAD

**Issue by NiOHar** [ls1intum/Artemis#1471]
### Describe the bug
In the L04E01 quiz in EIST 2020, one answer has been declared invalid. Artemis says that I have marked all answers correctly, but it still displays 0/1 points for that question

#### To Reproduce
I don't know how exactly the change was made, but I guess it occurs everytime a answer is marked as invalid after the deadline

#### Expected behavior
The score should be 1 of 1

#### Screenshots
![grafik](https://user-images.githubusercontent.com/52559465/81927390-d7de3400-95e3-11ea-9a4d-d1a893e35347.png)
![grafik](https://user-images.githubusercontent.com/52559465/81927400-ddd41500-95e3-11ea-9bb4-4ab06a4fe686.png)

### Environment

<details><pre>
 - OS: Windows 10 (x64)
 - Browser Firefox
 - Version 76.0.1
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by tiffca** [comment]
Reproduce steps: 

1. (Instructor) Create a live quiz, all or nothing grading, with at least 2 possible correct answers. 
1. (Instructor) Release the quiz 
1. (Student) Complete the quiz, mark only one of the answers valid (so your result would be 0/1 because it's all or nothing)
1. (Instructor) Re-evaluate the quiz. Mark one of the correct answers as invalid (choose an answer that was not selected by the student) and save
1. (Student) Check the quiz results. Expected: the results should give full points based on the new options. Actual: the student still has 0/1 points.


 

1.

**Comment by krusche** [comment]
I just tested it and except some user interface display issues in the reevaluate dialog, this works as intended. Please note that we did not fully reevaluate the quiz in EIST until now.
@NiOHar please have another look (refresh the page) and feel free to reopen the issue in case the problem still exists

**Comment by NiOHar** [comment]
Yep, it's fixed now. Thanks!
