### ISSUE TITLE
Unassesed submissions affecting student statistics

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1514]
### Describe the bug
Not yet assessed submissions affect the statistics of the students because they are handled as "all wrong" or at least count towards the max score
However this makes the statistic basically useless since it doesn't tell anything then.

#### Expected behavior
Only assessed exercises affect the statistic.
In the example below the Text Exercises should only have 12pts max score and the relative score should therefore be 100%. 
In addition it might be better to remove the blue bar to better indicate that it's unassessed. Or add an explaining legend. But I think no color (transaprent) would be more intuitive.

#### Screenshots
This is an example from a student.
![weird_statistic](https://user-images.githubusercontent.com/64264938/82759968-d802de80-9df0-11ea-8b89-0d3f348d3eb2.png)

**Comment by krusche** [comment]
@julian-christl I get your point, this is not 100% trivial, because different exercise types have a different logic when the submission is assessed:
1) Quiz exercises are assessed immediately when they are due
2) Programming exercises (with automatic assessment only) are assessed before they are due, but the result might not be final
3) Modeling exercises, text exercises, file upload exercises and programming exercises with manual assessment are assessed at some point. We have to distinguish different cases:
a) If the assessment due date is set, students see the result right after the assessment due date passes, if it was corrected in time (Before the assessment due date, the result can change). If their assessment is overdue, then, they see it as soon as the result is available.
b) If no assessment due date is set, students see the result immediately when it is produced.
4) In addition, there are cases with late submissions (result is unrated) or without submission.

Please note, that results still could change, e.g. due to complaints.

It would be desirable to keep the logic of the statistics simple, i.e. the same logic for each exercises type, so that everyone understands it, however this is not really possible without compromises. So the question is at which point (based on the exercise configuration) does the total max score in the statistics increase? 

* When the exercise is made available (release date)? 
* When the exercise is due? 
* When the assessment is due? (notice, not all exercises are required to have one, so how do you handle exercises without assessment due date?)
* When the result is available? (this would actually lead to the case that each student might see a different total max score, which would be confusing in case students compare their statistics)

We could also add more details and add a value "total reachable score", then the max score would be consistent (based on the release date of exercises), however this would add additional complexity.

In case you have a good idea for a logic how to calculate the score "correctly" and "understandable", please let me know.

So, I would not say "However this makes the statistic basically useless since it doesn't tell anything then.", just because they are a bit behind. The total score is misleading and we should improve this, but as you see, this is not as easy as you might think!

**Comment by julian-christl** [comment]
@krusche 

About your last point: I actually think it's useless because until the end of the semester there are always some unassessed exercises. To get a full percentage you'd therefore have to recalculate the statistics anyway (to know how well you are doing regarding the bonus). This has to be done by scrolling through all exercises, adding up all points and calulating the percentage. You do nothing else with the statistics. So until they represent the actual value you'd have to recalculate on your own anyway to get the percentage.
That's what I mean with "basically useless".

But yes, I get your point and will think myself about a possible solution. Probably we'll finde something nice.

**Comment by julian-christl** [comment]
@krusche 
I took a look in the code and thought about it.
This should be the method in which all points are calculated.
https://github.com/ls1intum/Artemis/blob/cd33bd13b0c8ee037d014a67c36a53c476dc0c5a/src/main/webapp/app/overview/course-score-calculation.service.ts#L22-L53
There are the following constraints when the `absoluteScore` is incremented compared to the `maxScore`:
- `participation !== null`
- `result !== null`
- `result.rated == true`

All these constraints don't count for the `maxScore`. However the `maxScore` should only be counted if
1. There is a participation where there is a result which was rated
2. Or there is no participation (if obviously there is no `dueDate` or it's already passed but that's already dealt with)

Therefore in my opinion this should be able to be done by changing to the following code where the `maxScore` incrementation was moved in the if clause where the `absoluteScore` is beeing incremented and additionally in the else clause of the `participation` nullcheck:
```
if (exercise.maxScore != null && (!exercise.dueDate || exercise.dueDate.isBefore(moment()))) {
    const participation = this.getParticipationForExercise(exercise);
    if (participation !== null) {
        const result = this.getResultForParticipation(participation, exercise.dueDate!);
        if (result !== null && result.rated) {
            let score = result.score;
            if (score === null) {
                score = 0;
            }
            absoluteScore = absoluteScore + score * this.SCORE_NORMALIZATION_VALUE * exercise.maxScore;
            maxScore = maxScore + exercise.maxScore;
        }
        presentationScore += participation.presentationScore !== undefined ? participation.presentationScore : 0;
    } else {
        maxScore = maxScore + exercise.maxScore;
    }
}
```

Since I do note have a working local environment but only the code I was not able to test if this actually does what I think it does but I'm looking forward to your response.
This solution should be independent from any exercises types.
Let me know if I miss there something.
