### ISSUE TITLE
Character limit without symbols and whitespaces

### ISSUE THREAD

**Issue by ptudorr** [ls1intum/Artemis#1577]
### Is your feature request related to a problem?

What's the point in counting white spaces and symbols? How is this helping anyone? Or why are you doing this? I mean the point is not to write stories, because the tutors don't have time to read everything, right? But you don't need time to count white spaces and symbols.
### Describe the solution you'd like

In text exercises the character number should be just with numbers and letters, without white spaces and symbols.
### Describe alternatives you've considered

There is no alternative. It's pretty basic. Just don't count the white spaces and the symbols from the text field.
### Additional context

I often use a lot of symbols ( , : - * . ; ! ?) so instead of “Portability vs Efficiency” - 23 char, I have “-Portability vs. efficiency:” - 26 char. You would say that 3 characters are not a big difference/problem, but if you have for example 5 design goal trade-offs, plus the normal punctuation, the character numbers will rise up pretty quickly. And let’s be honest, you don’t need longer time to read sentences in wich we are using punctuation correctly or different symbols. I think that the character limit is a good idea, because in this way we are forced to write just the important things and not stories. But I also do think that you should think a little bit more about this problem and come up with an idea that should fit to our problem.

**Comment by just-max** [comment]
This seems to create additional complexity where it is not really necessary.
First of all, I have never seen a text submission box that doesn't count either all characters or all characters without white space. The submission box could display both?
Additionally, the character count is not a limit in anyway. If your submission is 13% longer (going off of 26 vs 23 characters which is arguably an extreme example), say 1130 instead of 1000 characters, it will still be evaluated. 
Finally, adding those symbols does add information like any other character. I think it therefore makes sense to count them. At this point it becomes a matter of which characters do you/don't you count for something that is just a guide anyway.

**Comment by ptudorr** [comment]
![C5FEAE8F-C7F6-4DDA-B5CD-A09FC32CD4C9](https://user-images.githubusercontent.com/33669868/83922122-79dae180-a788-11ea-886b-58da78c404a0.jpeg)

**Comment by ptudorr** [comment]
And ok, if you say that you never saw "a text submission box that doesn't count either all characters or all characters without white space", then why is this counting wrong? :)))

<img width="956" alt="Captură de ecran din 2020-06-06 la 09 29 03" src="https://user-images.githubusercontent.com/33669868/83937805-aa4a6c00-a7d8-11ea-9d05-d17c7582db4d.png">


<img width="770" alt="Captură de ecran din 2020-06-06 la 09 29 19" src="https://user-images.githubusercontent.com/33669868/83937807-ad455c80-a7d8-11ea-9b72-9da27ac97384.png">

**Comment by ptudorr** [comment]
There is a difference of 10 words... =)))

**Comment by krusche** [comment]
@ptudorr 

The character limit announced in EIST is **not** a hard limit. It should give you an idea of how much is expected. To be honest, I personally don't like something like this, because the character length does not tell anything about the quality of the answer. But I can also understand the tutors, think about reading 1500 submissions with 1000 characters or with 2000 characters.

Still, we see this as soft limit and I asked the tutors to also correct submissions above the limit and only refuse the correction if students exceed the limit by more than 100%.

Coming back to the character / word count in Artemis. To be honest, I don't think it makes a big difference, but we can exclude whitespaces as well. However, please keep in mind that we currently focus on other implementations and therefore, I consider this as a low priority feature.

**Comment by ptudorr** [comment]
Thank you for the nice words. This is the best explanation I've received so far. I perfectly understand now, what the situation is!

**Comment by ge65cer** [comment]
The only hard limit is 30.000 characters as of https://github.com/ls1intum/Artemis/pull/5706.
