### ISSUE TITLE
Add export/import functionality to model exercises

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1579]
Especially relevant for team exercises since studenty might want to export there submission and modify it afterwards.

- Export should always be available
- Import only before duedate

(As discussed)

**Comment by krusche** [comment]
I don’t think we should add this because it would simplify cheating!

**Comment by julian-christl** [comment]
Then at least we should add an export functionality for given argument and probably for only the team model exercises.
I can't see how this would simplify cheating however it would make it way more easy for the students to make an updated version they can provide their tutor if something changed.

What do you think about that @krusche ?

**Comment by TobiasPr** [comment]
It is already possible to copy and paste diagram elements (also the whole diagram), so from the cheating aspect thats already given in my opinion. Waiting with implementation until clarification.

**Comment by krusche** [comment]
> It is already possible to copy and paste diagram elements (also the whole diagram), so from the cheating aspect thats already given in my opinion.

There is a big difference between copy / paste and import / export, though!

We should not make cheating easier, and I don't want to have this feature in Artemis for now. We intentionally designed the modeling editor in a way, that cheating is difficult! Therefore, I'll close this issue!

If copy and paste is easily possible between multiple browser windows/tabs, we should revert this, so that in Artemis, you can only copy and paste elements within a model of the same browser window / tab!

**Comment by julian-christl** [comment]
@krusche I don't endorse closing this since the issue with the export functionality it not resolved yet.
I can't see how it improves cheating but I can see how it would improve the workflow for team modeling exercises.

**Comment by krusche** [comment]
Then I suggest you specify this in more detail in a separate issue what you exactly mean. Please follow the issue template!

We could allow students to export a PNG or PDF vector graphics.

Another option would be to provide a link to open the same model on apollon.ase.in.tum.de.

However, it should never be possible to import a model in Artemis because students would abuse this to cheat!

**Comment by julian-christl** [comment]
I'll do, I only didn't do it here because I've already discussed it with Tobias and wanted to save some time ^^
