### ISSUE TITLE
The online editor shows "Unsaved" but "Submitted"

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#1854]
### Describe the bug
When editing a file with the online editor, the status at the bottom of the file browser says "Unsaved", but the "Submitted" does not change to "Unsubmitted".

#### To Reproduce
1. Take an exam with a programming exercise
2. Edit a file in that exercise
3. Observe the status buttons at the bottom of the file browser

#### Expected behavior
When there are unsaved changes, these changes are also not committed. Therefore, the status should also change to "Unsubmitted" in this case.

#### Screenshots
![Screenshot_2020-07-10 Exam(1)](https://user-images.githubusercontent.com/2746810/87145919-70bec200-c2aa-11ea-9f60-189a339f3f88.png)

### Environment
Firefox on MacOS

**Comment by krusche** [comment]
Some explanation why this is the case: The client tracks two different states here, the save state (sync between client and Artemis server with the save button) and the commit state (sync between Artemis server and the remote repository on Bitbucket).

If the changes are not yet saved on the server (== Unsaved), nothing can be synced between the Artemis server and the remote repository, therefore the commit state is still green.

I agree that this might be confusing and we should probably change the visualization to the client so that it cannot be submitted in case it is unsaved

**Comment by krusche** [comment]
@kloessst @anditurdiu could you please have a look at this?
I agree that this might be confusing so we should fix this, however it's not a critical issue and has a rather low priority

**Comment by anditurdiu** [comment]
This was fixed in #2228
