### ISSUE TITLE
Back button does not work for the assessment of team exercises when you are just a tutor

### ISSUE THREAD

**Issue by fde312** [ls1intum/Artemis#1895]
### Describe the bug

When assessing a team exercise and afterwards you click on the back button, you get a null pointer exception. See screenshot below:
![image](https://user-images.githubusercontent.com/41108487/87683423-5a6ca680-c781-11ea-8349-81f4395afb6c.png)

Somehow this worked for instructors or admins but not for just tutor accounts on ts1.
 
#### To Reproduce

1. Assess a Team Exercise
2. Click on Back button

#### Expected behavior

You should be able to go back to the teams submissions view

**Comment by tiffca** [comment]
it seems this line of code is throwing an error _for tutors only_, looking into why/how this could happen 

![image](https://user-images.githubusercontent.com/63906424/88932729-c1f51c80-d27e-11ea-9c0d-6f29dab09574.png)

**Comment by tiffca** [comment]
hey @anditurdiu , @JonasPetry  - I see you edited this file within the past month. Can you please offer a hint of what could be the issue? I made some changes here ([commits](https://github.com/ls1intum/Artemis/commits/bugfix/team-exercises/back-button-not-working)), but no luck yet. I know it's exams so no worries if not. I can check with others as well.

**Comment by tiffca** [comment]
this looks a bit more complex than it appears, since the Team object itself is showing as null, so I'll un-assign for now. Leaving the branch/build info here in case it helps someone else. Feel free to delete it. 

https://bamboo.ase.in.tum.de/browse/ARTEMIS-WEBAPP1485
https://github.com/ls1intum/Artemis/tree/bugfix/team-exercises/back-button-not-working
