### ISSUE TITLE
Quiz question was marked as invalid in the summary

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#1911]
### Describe the bug
A quiz question had a red label in the summary, that said "This question is invalid and will be assess as complete correct".

Generally, it is a good thing, that participants of an exercise are informed, if the exercise is considered invalid. However, it is unlikely, that this decision is being made immediately after the exam, so this message is shown in the summary.

Maybe, the exercise has been flagged as invalid in another course, then exported and then imported for this test exam. In this case, it would be great, if importing an exercise had a warning about invalid exercises and the functionality to remove the flag.

The error message with improved grammar is: "This question is invalid and will be assessed as completely correct". However, this is still not entirely correct, since the assessment is not about the question, but the submission. A proposal to correct this: "This question is invalid and your submission will be considered being completely correct".

#### Screenshots
![Screenshot_2020-07-17 Exam(3)](https://user-images.githubusercontent.com/2746810/87795307-29a37480-c848-11ea-8e34-e51857033573.png)

### Environment
Firefox on MacOS

**Comment by krusche** [comment]
Not a high priority, because we should double check this in case we import quiz questions into the exam.
I agree that the import should warn the instructor in case there are invalid questions or answer options

I guess we can also add an error message in the validation of quizzes at the bottom, in case a quiz has invalid questions or answer options during edit, so that instructors cannot save. Before an instructor "re-evaluates" a quiz, there should be no invalid questions or answer options!

I like the improved phrasing "This question is invalid and your submission will be considered being completely correct".
