### ISSUE TITLE
Apollon crashes ocassionally on multi-select

### ISSUE THREAD

**Issue by patrisvalera** [ls1intum/Artemis#1939]
### Describe the bug

I was doing the test and is was working fine, but suddenly everything became write and no exercises were shown(all of them not just one). I did not press anything or do anything. Then I had to reload the page and then it was working again. 

#### Expected behavior

The test running without problems and no such problems in the reals exam.

#### Screenshots

<img width="1424" alt="Screenshot 2020-07-20 at 9 26 14 AM" src="https://user-images.githubusercontent.com/66625445/87910926-191f1400-ca6b-11ea-8e9e-fb267dcc011c.png">

### Environment

<details><pre>
 - OS: MacOS
 - Browser: Google Chrome

</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
Can you please post the full video, I only see a screenshot.

We try to fix the problem if we can reproduce it.

Apart from that, if such an issue should occur again, you should definitely reload the page!

Did you notice any error messages in the console?

Would you mind sharing your TUM identifier with us so that we can look into the system Logs and into the database if we find something? You might also want to send this via email or slack to me.

Also: when exactly did the error occur?

**Comment by kloessst** [comment]
I got a similar error playing around with multi-select in a course modeling exercise. I also captured the console errors. It seems like the error originates in Apollon.

![ApollonWhitescreen](https://user-images.githubusercontent.com/16407766/88086010-f41fc380-cb86-11ea-8755-3bcc2f2e6c6a.PNG)
