### ISSUE TITLE
Finishing after grace period doesn't show error

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1941]
### Describe the bug
When you let the grace period run out and enter your name you are able to click on fnish. Doing so will result in a 403 call however no error is shown to the user.

#### To Reproduce
1. Participate in an exam
2. Wait for the grace period to pass
3. Check and Fill in your name
4. Click on finish
5. See that nothing happens (watch the 403 in the Dev-Tools)

#### Expected behavior
Either make the button non clickable even if you enter the name and check the checkbox (with an additional information please) or show an dedicated error message if the call returns a 403.

#### Additional information
Ciritical because it can cause confusion in the exam which we want to prevent. And it should be easily resolved.

**Comment by krusche** [comment]
Yes, this is also on my list that we should show an error message here. Also in other cases when the corresponding REST call fails (for whatever reason). It would also be good, if the Finish button has an animation when you press it and gets locked, so that you cannot press it twice accidentally. (if this is not the case yet)

Another problem: this screen stays open when students reload the page and currently will "remain" forever.
After the grace period is over, we should show a message like e.g. "You have not submitted your exam on time. It will not be graded!" below the exam header information. All other elements (exam end text, exam confirmation text, checkbox, name input field, Finish button) should then be hidden.

During the assessment of the exam, we can then filter out such student exams, because we do not need to correct them.
(Should be done in a follow-up)
