### ISSUE TITLE
Manual Assessment Draft visible in Code Editor before Due Date

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#2131]
### Describe the bug
In exercises with a manual review and a assessment due date the manual feedback is visible to students too early in the code editor.

#### To Reproduce
1. Create a programming exercise with manual review and a review due date.
2. Create a student submission.
3. After the due date create a manual assessment as a tutor. Only Save it, do not Submit.
     - In the tutor dashboard it now has the status ‘DRAFT’.
4. Student View:
    - In the personal overview over all currently running exercises: Marked as ‘No graded result’.
    - In the code editor of this exercise: Feedback with points and comment is already visible.

#### Expected behavior
The manual feedback draft should not be visible to a student. It should only become visible after the assessment due date has passed.

#### Screenshots
In current exercises overview:
![Screenshot_20200928_124409](https://user-images.githubusercontent.com/64250573/94423206-8c8a8380-0188-11eb-912f-2244ad5fa700.png)
In the code editor view:
![Screenshot_20200928_124441](https://user-images.githubusercontent.com/64250573/94423207-8d231a00-0188-11eb-8ed4-4c976630b2ff.png)

**Comment by MaisiKoleni** [comment]
@fde312 could you have a look here?

**Comment by krusche** [comment]
I already asked @fde312 and he is investigating it. We will have a fix soon

**Comment by fde312** [comment]
This will be solved by the linked PR. The issue was that on the previous way to give manual feedback, you had to enter a result string and also a score. Therefore this was always stored into the database (also for safe) and displayed by the result label. 
With the new approach, the resultstring and score is calculated only after clicking on submit. Therefore no draft assessments are displayed anymore :)
