### ISSUE TITLE
Update node cause current version set seems to be incompatible 

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2160]
### Describe the bug
Running `./gradlew -PnodeInstall=true -Pprod -Pwar clean bootWar` outputs:
```
error autoprefixer@10.0.1: The engine "node" is incompatible with this module. Expected version "^10 || ^12 || >=14". Got "13.12.0"
```
Where 13.12.0 is installed because it is set so in gradle.properties. So it seems either should autoprefixer we downgraded or node upgraded. The latter seems to make more sense.

#### To Reproduce
Running `./gradlew -PnodeInstall=true -Pprod -Pwar clean bootWar` 

### Environment

<details><pre>
 - OS: Ubuntu
 - Branch: develop
</pre></details>

**Comment by axel1200** [comment]
Updating it fixes it

**Comment by axel1200** [comment]
I can make a PR but since changing the node version might have a lot impact I would suggest some maintainer does so

**Comment by krusche** [comment]
please provide a PR, thanks

**Comment by krusche** [comment]
I guess we can go to node 14. It's out there since quite some time and the support in the build infrastructure should be available so that we do not get any error messages.
We just have to be careful, that there are not issues in Github actions or in Bamboo, so please do not choose the latest node version

**Comment by krusche** [comment]
I updated it to 14.0.0 on `develop`
