### ISSUE TITLE
Improve error message when the build is still running

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#2329]
We currently have a timeout of 2min in the Artemis client for builds before a red button is shown to trigger the build again.
This works quite nicely when the notification of the build system did not reach Artemis for some reason.

However, due to recent changes, it does not handle the case well that the build is still running (there might be builds that take longer than 2min, e.g. due to queuing or due to issues in the tests) and shows a problematic error message:

![image](https://user-images.githubusercontent.com/744067/98013200-59c45280-1dfa-11eb-8b60-5b67fa224c79.png)

The problem is the exception of Bamboo when triggering the build because Bamboo is configure to only allow one build at the same time (to prevent spamming and filling the queue to easily). 

I think we should implement the following improvements here:
1) Before we trigger a new build, we first check the build status of the build plan. In case it is still running, we tell the client to wait longer (another 2 minutes). The client then simply shows again the animation and waits another 2min before the red trigger button is shown again
2) We handle the exception of Bamboo that is reported over REST in this case, and also tell the client to wait longer (as defined in 1)

**Comment by schultek** [comment]
This is what I have found so far: 

1. The 'trigger-failed-build' endpoint already handles the case where a submission is already building on the CI server and handles this by re-notifying the user about the existing submission without triggering a new build.

2 .I have found the following comment in the source code:

     * Create a submission with given submission type for the last commit hash of the given participation.
     * WARNING: The commitHash is used to map incoming results to submissions. Using this method could cause the result to have multiple fitting submissions.
     *
     * See discussion in: https://github.com/ls1intum/Artemis/pull/712#discussion_r314944129;
     *
     * Worst case scenario when using this method:
     * 1) Student executes a submission, the build is created on Bamboo
     * 2) The build takes longer than 2 minutes, this enables the student to trigger the submission again
     * 3) A new submission with the same commitHash is created on the server, there are now 2 submissions for the same commitHash and 2 running builds
     * 4) The first build returns a result to Artemis, this result is now attached to the second submission (that was just created)
     * 5) The second build finishes and returns a result to Artemis, this result is attached to the first submission
     *

This talks about a related issue with two concurrent running builds, but I think this is outdated because of the fact that bamboo only allows one concurrent build (nowadays? maybe this was different at the time the commit was made - August 2019) and because of the behavior described in (1.) which was implemented in November 2019.

As of this i don't really understand why apparently a second build is triggered anyways. I have to further investigate this issue.

**Comment by krusche** [comment]
I guess you would need to debug this case by creating a scenario where the build takes longer than 2min to understand what's going on exactly.

Maybe, `getBuildStatus` in BambooService is not working correctly at the moment? We did some refactoring here recently and might have missed one specific case
