### ISSUE TITLE
Redesign user tracker into user statistics

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2334]
### Describe the bug
User tracker not displaying anything

#### To Reproduce

1. Open User tracker as admin

#### Screenshots
![Screenshot from 2020-11-03 21-36-02](https://user-images.githubusercontent.com/19996713/98037932-a0c33f80-1e1c-11eb-8fa3-28a61de4b0d8.png)

#### Output in Web Console
```
window.controllers/Controllers is deprecated. Do not use it for UA detection. index.js:1362
Cookie “XSRF-TOKEN” has been rejected because it is already expired. info
Some cookies are misusing the recommended “SameSite“ attribute 2
Cookie “cookietest” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite fp.esm.js:292:21
Cookie “cookietest” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite fp.esm.js:296:30
Cookie “XSRF-TOKEN” has been rejected because it is already expired. account
Cookie “XSRF-TOKEN” has been rejected because it is already expired. 4 time
Cookie “XSRF-TOKEN” has been rejected because it is already expired. notifications
Cookie “XSRF-TOKEN” has been rejected because it is already expired. time
Cookie “XSRF-TOKEN” has been rejected because it is already expired.
```

**Comment by krusche** [comment]
This was deactivated intentionally some time ago.

**Comment by axel1200** [comment]
ok well then maybe we should just removes it. Looks broken otherwise

**Comment by krusche** [comment]
Yes, I think we can remove it. It does not bring much functionality at the moment.

@FrankeLukas could you simply remove all related pages and functionality?

**Comment by krusche** [comment]
I just had an idea. Instead of removing this page, we should rename it and show the following interesting activities / metrics:
1) How many unique users have logged in to Artemis in the last X days
2a) How many unique users have participated in an exercise (i.e. have a submission with a submission) in the last X days
2b) How many total submissions (submission date) have been made in the last X days
3) How many results (with how much feedback) have been created (completion date) in the last X days
4) How many unique tutors have corrects an assessment (i.e. there is a manual result with completion date) in the last X days
5) How many exercises have been released in the last X days
6) How many exercises have been due in the last X days
7) How many exams have been conducted, how many individual student exams have participated (based on submissionDate) in the last X days

X should be a variable that can be specified on the page, e.g. 3, 7, 30, 90, 180, 365

There are probably more statistics that might be interesting.

**Comment by krusche** [comment]
All those activities / metrics / stats would be interesting on a global Artemis level, but also on a course level. So this might also related to @FuchsDominik's thesis about teaching analytics. I guess we could start here with the global stats and even provide (bar/line) charts on a weekly basis in the last X days...

**Comment by krusche** [comment]
Here is a SQL query to find the number of distinct users who logged into Artemis in the last 7 days

```
SELECT
	count(DISTINCT u.login)
FROM
	jhi_user u,
	jhi_persistent_audit_event a
WHERE
	u.login = a.principal
	AND a.event_type = 'AUTHENTICATION_SUCCESS'
	AND a.event_date >= DATE(NOW()) - INTERVAL 7 DAY
	AND u.login NOT LIKE '%artemis_test_user%'
```

**Comment by krusche** [comment]
Here is a SQL query to find the number of distinct submissions in the last 7 days

```
SELECT
	count(DISTINCT u.login)
FROM
	submission s,
	participation p,
	jhi_user u
WHERE
	s.participation_id = p.id
	AND p.student_id = u.id
	AND s.submission_date >= DATE(NOW()) - INTERVAL 7 DAY
	AND u.login NOT LIKE '%test%'
```

**Comment by axel1200** [comment]
That would indeed be really interesting

**Comment by FuchsDominik** [comment]
> All those activities / metrics / stats would be interesting on a global Artemis level, but also on a course level. So this might also related to @FuchsDominik's thesis about teaching analytics. I guess we could start here with the global stats and even provide (bar/line) charts on a weekly basis in the last X days...

Looks really interesting yes. I will assign this to me and will work on this.

**Comment by axel1200** [comment]
This is already in the newest version as far as I am aware.
