### ISSUE TITLE
Students don't have access to build plan (and output)

### ISSUE THREAD

**Issue by lukasstevens** [ls1intum/Artemis#2378]
### Describe the bug
After creating an exercise and switching on "Publish build plan", students can't access the build plan for their own repository. Is this intended behavior?

#### To Reproduce
1. Create an [exercise](https://artemis.ase.in.tum.de/#/course-management/87/programming-exercises/2180)
2. Publish the exercise
3. Switch on "Publish build plan"
4. The link to the build plan in the exercise description works as expected for instructors
5. Students get this [message](https://zulip.in.tum.de/user_uploads/2/cc/txjEdpjhEUIQpN3R2mWriYlZ/2020-11-10-16_13_16-Access-denied-LS1-Bamboo.png)

#### Expected behavior
Students should be able to access the build plan (and output)

**Comment by krusche** [comment]
which configuration are you using? This only works for Bitbucket/Bamboo at the moment, because user management in Jenkins is not yet supported.

**Comment by lukasstevens** [comment]
We are using bitbucket/bamboo.

**Comment by kappelmann** [comment]
For reference, [this is the exercise we are talking about](https://artemis.ase.in.tum.de/#/course-management/87/programming-exercises/2180).

**Comment by krusche** [comment]
Thanks for the link, is there a reason the students should have access to the build plan.

We have only used this option when students learn something about continuous integration (as part of the project management lecture). However, we have not used this option in the last 2 years, so I'm tempted to remove it from Artemis.

For a normal programming homework exercise, it does not really make sense in my opinion that students can access the build plan. Due to the additional rights, they could mess around some settings, e.g. use their own docker image, change the structure of the build so that it always reports success, checkout arbitrary repositories with arbitrary code on our build agents.

**Comment by krusche** [comment]
If the main reason is that students should see the build output, we should provide a way for this without the need to access the whole build plan. If the build fails, students can already see the build output. If the build passes and tests fail, it is typically not necessary to see the build output, because the important information should be part of the test failure message

**Comment by kappelmann** [comment]
`If the build fails, students can already see the build output.` Oh, that is indeed our use case. But if I click on `Build Failed` in the `Scores` view on an exercise, then it just tells me that there are no results available. That is, I click on `Build Failed` [here](https://artemis.ase.in.tum.de/#/course-management/87/exercises/2180/scores):
![image](https://user-images.githubusercontent.com/7101032/98919763-84379f00-24cf-11eb-933b-b1fd89687ea1.png)
and get this:
![image](https://user-images.githubusercontent.com/7101032/98919847-a2050400-24cf-11eb-8dff-cfce8dba52fd.png)

Are we doing something wrong?

**Comment by krusche** [comment]
@kappelmann it should not be the case that "No result details available" is shown here. We need to investigate why this is the case

**Comment by krusche** [comment]
just looked into the Artemis database, the build log is available. Have to check why they are not shown in the client

**Comment by krusche** [comment]
ok, I cannot find an issue quickly, we have to investigate the issue in more detail.
Could you create another issue with the actual problem that the build logs are not available?
We will try to fix the issue as soon as possible

**Comment by kappelmann** [comment]
Done: https://github.com/ls1intum/Artemis/issues/2392
