### ISSUE TITLE
Do not fork repositories on programming exercise import

### ISSUE THREAD

**Issue by kloessst** [ls1intum/Artemis#2451]
### Describe the bug
Programming exercises can't be imported because the maximum depth of the fork hierarchy exceeds 5.

Exemplary error message:
`"message":"GBS2021NTHREADS/gbs2021nthreads-exercise cannot be forked. For performance reasons, fork hierarchies are limited to a maximum depth of 5 beneath a given root repository. Please create your fork from a repository higher up in the hierarchy, such as GBS2021NPROZESSE/gbs2021nprozesse-exercise."`

The error and possible solutions are documented in the [Bitbucket documentation](https://confluence.atlassian.com/bitbucketserverkb/repo-cannot-be-forked-fork-hierarchies-are-limited-to-a-maximum-depth-of-5-872264209.html).

As a workaround, programming exercises higher in the fork hierarchy should be imported.
To prevent this error in the future, we should stop using forks to import programming exercises with Bitbucket.

#### To Reproduce

1. Import a programming exercise
2. Import the imported programming exercise
3. Repeat step 1. and 2. five times to produce the error.

**Comment by derLalla** [comment]
![image](https://user-images.githubusercontent.com/33484318/100092788-ed67cc80-2e56-11eb-8ca1-212a98163188.png)
![image](https://user-images.githubusercontent.com/33484318/100092826-fb1d5200-2e56-11eb-968c-c0274deb1312.png)
It seems like the api only supports creating forks instead of a clone. So we might need to find a way to only fork from the root?
