### ISSUE TITLE
Assessment Dashboard does not load

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#2596]
Dashboard is broken, Tutors cannot assess submissions anymore if they assessed (saved/submitted) at least one. 

## Sentry Issue
https://sentry.io/organizations/ls1intum/issues/2103235573/?end=2020-12-23T11:30:40&project=1440029&query=is:unresolved&sort=freq&start=2020-12-23T09:00:40&utc=true

## Screenshot
![image](https://user-images.githubusercontent.com/11130248/102989539-0f1ba880-4516-11eb-85a1-11bdf5d4a43e.png)

## Cause
![image](https://user-images.githubusercontent.com/11130248/102989343-c368ff00-4515-11eb-81a5-77a622c43a8d.png)
![image](https://user-images.githubusercontent.com/11130248/102989596-2d81a400-4516-11eb-9c17-2aea11817a98.png)

**Comment by MaisiKoleni** [comment]
I linked and merged some sentry issues here. Have a look at those as well, seems to be a problem at multiple places.

**Comment by krusche** [comment]
Thanks for the detailed report @MaisiKoleni 
@SimonEntholzer @nicolasruscher we should always avoid using `null` in the client code and instead use `undefined`.
When it comes to checks for `undefined`, please always use `!=` and `==` instead of `!==` and `===`.
And try to avoid the use of the force operator `!` to avoid compile errors / warnings. There is a good reason for those compile errors / warnings, in particular if variable values can be undefined.
This is also part of our client coding guidelines. If it is not really clear there, we should update those as well.

**Comment by krusche** [comment]
Should be fixed now. It is currently deployed to production. Please check if it works.
In case you'll find additional or related issues, feel free to reopen this issue.
