### ISSUE TITLE
Exercise assessment dashboard displaying all assessments as draft

### ISSUE THREAD

**Issue by Trattue** [ls1intum/Artemis#2733]
### Describe the bug
Graded exercises appear as drafts in the exercise assessment dashboard and the date of the last build is shown. Feedback and grading remains saved in the exercises, so this seems only to affect the exercise assessment dashboard.
This issue is not present at older exercises with their assessment due dated already passed (can't confirm whether assessments submitted before the Artemis update with their due date not passed yet are affected or not).

#### To Reproduce
1. Start a new assessment
2. Add feedback, submit the assessment
3. Click "Assess Next Submission" (not sure if this is necessary for reproducing)
4. Open the exercise assessment dashboard for the exercise

#### Expected behavior
The exercises should be shown as graded with their score shown.

#### Screenshots
Exercise Assessment Dashboard (these exercises are all graded and are displayed wrongly):
![grafik](https://user-images.githubusercontent.com/63713970/105608872-d6d1e900-5da5-11eb-8025-d5d5e2e7f05a.png)

Assessment after opening via the exercise assessment dashboard (feedback and grading remain saved correctly, "Override assessment" and "Assess Next Submission" button are displayed correctly):
![grafik](https://user-images.githubusercontent.com/63713970/105608895-0e409580-5da6-11eb-92c0-41f0156c656a.png)

### Environment
<details><pre>
 - OS: Windows 10
 - Browser: Latest Firefox, latest Google Chrome
 - Artemis version: 4.9.1
</pre></details>

#### Additional context
This seems to be a regression after having Artemis 4.9.1 deployed.

**Comment by MaisiKoleni** [comment]
Note: many (all?) PGdP tutors have this problem, and it is not clear, if this is just a client issue or an issue with the object in the DB or the way it is retrieved as well. "This issue is not present at older exercises" indicates that newer assessments are now treated differently. We will delay releasing the manual results to the students while it is not clear what the effects are.

**Comment by krusche** [comment]
Which exercise is affected? I can look into the database and check if the values are correct. I assume this is the case, otherwise the values could not be displayed correctly in the assessment.

So I assume this only affects the exercise dashboard. Have you looked into the scores page and into instructor exercise dashboard (in terms of completed assessments) whether the values are displayed correctly?

**Comment by Trattue** [comment]
One exercise affected in the PGdP course is [2703](https://artemis.ase.in.tum.de/course-management/83/exercises/2703/tutor-dashboard). The scores page displays everything correctly. The progress bar for completions in the course assessment dashboard seems to be correct (I can't confirm that though).

**Comment by krusche** [comment]
Our developers have a fix ready. After some additional testing, we will deploy a hotfix

**Comment by SimonEntholzer** [comment]
The bugfix is in [https://github.com/ls1intum/Artemis/pull/2734](url) :D

**Comment by Strohgelaender** [comment]
The draft-bug is fixed now, but the submission date shown in the exercise assesment dashboard is still the date of the last student submission, not the assessment date.
