### ISSUE TITLE
Make Courses / Exercises work like links

### ISSUE THREAD

**Issue by Strohgelaender** [ls1intum/Artemis#2820]
### Is your feature request related to a problem?
Artemis 4.9.4 now thankfully has buttons which work like links (#611, #2669). But this functionality is missing for courses in the Course Overview and for exercises of a course. Opening multiple exercises in multiple browser tabs still requires to manually navigate through Artemis over and over.

### Describe the solution you'd like
Courses and Exercises also have link-like features (open in new Tab, middle mouse button).

### Describe alternatives you've considered
Leave everything as it is ¯\_(ツ)_/¯

**Comment by krusche** [comment]
We have started with integrating this into the course administration mainly and will soon also integrate this into the course overview.

**Comment by emergenz** [comment]
Any news on this? This seems like a relatively easy fix, but is a very frustrating issue right now.

**Comment by krusche** [comment]
We try to prioritize this in the development. @FrankeLukas wanted to implement this as part of his bachelor thesis, but unfortunately, he was not able to finish all pages.

**Comment by bauen1** [comment]
The PR #4409 doesn't quite work as advertised, while e.g. the course is now a link allowing a proper context menu with the "Open in new Tab option", other expected behavior doesn't work.

When shift+clicking, the expected behavior would be to change nothing in the current tab and open the link in a new tab.
Opening the new tab works as expected, however some javascript catches the click event, ignores the shift and emulates the behavior of clicking the link.

**Comment by bauen1** [comment]
In particular it's probably https://github.com/ls1intum/Artemis/blob/3537a6aa62a835dd473709a2e8191b68e42e6f4d/src/main/webapp/app/overview/course-card.component.ts#L94-L99

**Comment by krusche** [comment]
Thanks for letting us know, we will look into it again
