### ISSUE TITLE
Delete Students from exam without having to click checkbox

### ISSUE THREAD

**Issue by SimonEntholzer** [ls1intum/Artemis#2951]
#### To Reproduce

1. Go to an exam, to "student-exams" 
2. Click on 'remove'.
3. The pop up asks to click a checkbox before you can remove the student from the exam
4. Click 'remove' in the popup without clicking the checkbox -> the student gets removed anyway.

#### Expected behavior

It is necessary to click the checkbox.

#### Screenshots

![image](https://user-images.githubusercontent.com/33342534/109801660-0f73a680-7c1f-11eb-9070-9aa024b599b9.png)
![image](https://user-images.githubusercontent.com/33342534/109801598-f8cd4f80-7c1e-11eb-98c4-9e736beaf064.png)

**Comment by krusche** [comment]
Good finding. I think we should fix this so that no one accidentally presses the Remove button

**Comment by krusche** [comment]
Sorry, I was wrong, the option additionally deletes objects in the database. We only need to rephrase it into

"Additionally delete..."

I suggest, if this option is selected, that the user has to type in the login of the student, so that this does not happen accidentally. We should also state that this action can **NOT** be undone (as we do it in other places)
