### ISSUE TITLE
Grading and csv-export for TUMonline

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#3037]
### Is your feature request related to a problem?
No, it's just a nice-to-have feature.

It would be great, if it was possible to export a csv, that can be uploaded to TUMonline in Artemis. For that, it is of course also necessary to enter a mapping from points to grades in Artemis.

### Describe the solution you'd like
I like the feature in TUMexam, that it can do the grading and produce a csv for TUMonline, but I find its separate definition of the grade table and the many steps that are required to apply it unnecessarily complex. I suggest to have all of the following on one web-page:
- a UI, where the point thresholds for the grades can be entered
- a simple generator to automatically generate the thresholds from few values (e.g. threshold for a 4.0, threshold for a 1.0, allow half points)
- a plot for all participants of the exam with number of points on the x-axis, number of students on the y-axis and dashed lines, where the current thresholds are.
- a plot for all participants of the exam with the grades on the x-axis and the number of students on the y-axis
- a table with the data for TUMonline (including its weird column names)
- a button to export the table as a csv-file (semicolon-separated, with german commas to separate the decimals of the grades, etc.)

**Comment by krusche** [comment]
@ivohashamov just started to work on the mapping from scores to grades. I am not sure if we can easily export a fully compatible csv file for TUMonline, because the csv file contains information that is unknown to Artemis. So, it would be necessary to upload the file first, store all data (that is not yet stored in Artemis such as TUMonline db keys) to be able to export the data again.

But grades and nice graphs are definitely on the roadmap and will soon be available

**Comment by krusche** [comment]
This feature has been implement, we are still working on some fine-tuning, but in general the functionality should work.
@JonasSC let us know what you think about it
