### ISSUE TITLE
Jenkins breaks user services

### ISSUE THREAD

**Issue by LDAP** [ls1intum/Artemis#3041]
### Describe the bug
Seems like #2959 (@ivanchimeno) introduces a number of issues.

#### To Reproduce
1. Start Artemis
- stack trace: [update-admin.log](https://github.com/ls1intum/Artemis/files/6156470/update-admin.log)
```
00 Bad Request: [{
artemis-be_1  | "servlet":"Stapler",
artemis-be_1  | "message":"Cannot delete self",
artemis-be_1  | "url":"/user/artemis/doDelete",
artemis-be_1  | "status":"400"
artemis-be_1  | }]
```

or

1. Start Artemis
2. Reset password
- stack trace [reset-pw.log](https://github.com/ls1intum/Artemis/files/6156463/reset-pw.log)

### Environment

 - OS: https://github.com/LDAP/docker-compose-artemis
 - Commit: a1da6936a11c33db9bc9763a89062773613f709a (aa7bd6610eb905c8c35b7dd9833b29d6d7c4a0fd)

**Comment by LDAP** [comment]
https://github.com/ls1intum/Artemis/blob/ba259c2923f967aefc87b07b5e2f983937242947/src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/JenkinsUserManagementService.java#L87

The caller does not guarantee that the groups are loaded. That may be the reason why password reset fails.

**Comment by LDAP** [comment]
@ivanchimeno 
Is there a reason, that the user is created in the VCS but not in CI when calling `registerUser`:
https://github.com/ls1intum/Artemis/blob/ba259c2923f967aefc87b07b5e2f983937242947/src/main/java/de/tum/in/www1/artemis/service/user/UserService.java#L247-L249

**Comment by ivanchimeno** [comment]
Thanks for reporting that bug @LDAP! For some reason, my local environment did not have these exceptions.

Regarding the issues:

1. You're correct, `registerUser` needs to create a new Jenkins user. I somehow missed this function.
2. The password reset failure is indeed linked to groups not being loaded. I changed the `JenkinsUserManagementService` class to reflect your suggestion in [this branch](bugfix/jenkins-user-management/various-issues). 
3. The issues you reported about the bad request, the problem is that when we update a user, we re-create it. This causes an issue when Artemis tries to update the admin user of Jenkins (if it's the only admin). If it's the only user, Jenkins doesn't permit us to delete. A possible workaround would be to create another Jenkins admin user. Another possibility would be to disable updating the internal admin account in Jenkins.
