### ISSUE TITLE
Missing indents in Text exercise

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#3450]
### Describe the bug
Students submit a text exercise with indents (e.g. a scenario or a use-case description where indents are expected).
After submission, everything works fine but after the grading, they are missing.

I assume this is due to Athene processing/Artemis processing for Athene the text. I expect this process to trim the found text before continuing which results in removing indents.

#### To Reproduce
1. Participate in a text exercise with indents
2. Grade this exercise 
3. You should already see that the indents are missing as tutor
4. The student should also see a new version without indents

#### Expected behavior
The indents don't get removed for students and tutors alike.
Either let Athene work with indents or send Athena trimmed version which is linked to the original untrimmed (if needed). But Athene **must not** change the submission.

**Comment by Strohgelaender** [comment]
Looking at the Server response of a test submission I noticed the following:

- All text blocks are trimmed. This is caused by https://github.com/ls1intum/Artemis/blob/d95c70027a3dedadcd5de733aac84933a8187d84/src/main/java/de/tum/in/www1/artemis/service/TextBlockService.java#L72 and #2891. The startIndex and endIndex still represent the additional chars used for the whitespaces, making the indentation visible in the assessment text editor.
- The text-Attribute itself does not contain the whitespaces (in the most cases ?). I couldn't figure out where and why these are removed.
- This also seems to cause no indentation at all being visible to the students, the text editor sees to show only the text contained in the text-attribute without looking at the text blocks.

You can find one test submission in the test course [here](https://artemis.ase.in.tum.de/course-management/122/text-exercises/4313/submissions/2663612/assessment).

**Comment by Dominik-Weinzierl** [comment]
Spaces and tabs are visible in the tutor dashboard, but not in the graded student submission.
Some screenshots to better understand the problem.

<details>
  <summary>Student view:</summary>
 
 ![image](https://user-images.githubusercontent.com/60005702/118693174-1c119f00-b80b-11eb-9040-7f68ed18a266.png)
</details>

<details>
  <summary>Tutor view:</summary>
  
![image](https://user-images.githubusercontent.com/60005702/118693300-3ba8c780-b80b-11eb-95dc-f8e67a0d48dd.png)
</details>
