### ISSUE TITLE
Creating C Programming Exercises Fails in Jenkins Setups

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#3484]
### Describe the bug
In a Gitlab+Jenkins setup the creation of programming exercises in Java or Python works, creating C exercises fails.

#### To Reproduce
In a Gitlab+Jenkins setup:
1. Try to create a new programming exercise with language `C` selected.
2. Notice that the creation fails with an error message 

#### Expected behavior
The programming exercise is created without error.

### Environment
 - Artemis: noticed on branch `feature/programing-exercises/jenkins-build-logs-on-new-result`, probably on `develop` as well as changes are unrelated
 - Jenkins: 2.293

#### Additional context
Jenkins Error:
```
org.xml.sax.SAXParseException; lineNumber: 132; columnNumber: 35; An invalid XML character (Unicode: 0x1b) was found in the element content of the document.
[…]
Caused: java.io.IOException: Failed to persist config.xml
```

Artemis Error:
```
Mai 25 09:55:17 artemis java[855]: de.tum.in.www1.artemis.exception.JenkinsException: Cannot give assign permissions to planBASE
Mai 25 09:55:17 artemis java[855]:         at de.tum.in.www1.artemis.service.connectors.jenkins.JenkinsBuildPlanService.givePlanPermissions(JenkinsBuildPlanService.java:237)
Mai 25 09:55:17 artemis java[855]:         at de.tum.in.www1.artemis.service.connectors.jenkins.JenkinsBuildPlanService.createBuildPlanForExercise(JenkinsBuildPlanService.java:83)
Mai 25 09:55:17 artemis java[855]:         at de.tum.in.www1.artemis.service.connectors.jenkins.JenkinsService.createBuildPlanForExercise(JenkinsService.java:87)
Mai 25 09:55:17 artemis java[855]:         at de.tum.in.www1.artemis.service.programming.ProgrammingExerciseService.setupBuildPlansForNewExercise(ProgrammingExerciseService.java:182)
Mai 25 09:55:17 artemis java[855]:         at de.tum.in.www1.artemis.service.programming.ProgrammingExerciseService.createProgrammingExercise(ProgrammingExerciseService.java:137)
[…]
```

**Comment by ivanchimeno** [comment]
I looked into the issue and the reason the exception is happening is because the template Jenkinsfile contains the `&#x1b;` code on line 87: `sed -i 's/&#x1b;//g' test-reports/tests-results.xml`. It looks like it's trying to replace ESC characters with an empty string. I'm not too sure why it's there and how we can encode the ESC so that it's readable in Jenkins but I would assume that we could just remove the line?

**Comment by b-fein** [comment]
I’m assuming there can be cases where the `tests-results.xml` could contain those characters (maybe as part of some colour escape sequences?). When the line is removed, the notification plugin would have to be able to handle the special character when parsing that file into the result sent back to Artemis. I do not know if that is the case.

**Comment by Wallenstein61** [comment]
> I looked into the issue and the reason the exception is happening is because the template Jenkinsfile contains the `&#x1b;` code on line 87 which cannot be read by Jenkins: `sed -i 's/&#x1b;//g' test-reports/tests-results.xml`. It looks like it's trying to replace ESC characters with an empty string. I'm not too sure why it's there and how we can encode the ESC so that it's readable in Jenkins but I would assume that we could just remove the line?

Just my two cents from the analysis of #3499:

The problem is not the XML-file. It contains valid XML. The Problem is in the source code that reads back the config.xml from jenkins  in `JenkinsJobService.getJobConfig`. It reads it correctly into a `org.jsoup.nodes.Document`, however seems to set the output-Options incorrectly. Thus serializing it back with `doc.toString()` returns a faulty XML with an unencoded ESC-character.

Michael
