### ISSUE TITLE
Don't highlight properties as wrong if there is no test case for them

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/Artemis#351]
### Is your feature request related to a problem?
![image](https://user-images.githubusercontent.com/10117554/56730238-b94a9800-6757-11e9-90b7-e80214cc7e69.png)

Student expects at least "title" to be correct, but not every attribute has its own test case. Since some other test is failing, all attributes are marked as wrong.

### Describe the solution you'd like
Don't "grade" properties that do not have specific test cases attached to them and leave them black.

**Comment by jpbernius** [comment]
Thanks for raising this issue. This is due to the way we perform those tests. We do tests in groups, so e.g. we test all attributes of a class. We do not want to bloat up the number of test cases here, so we do not intent to change the behavior right now. This is why I close this issue as **won't fix.**
/cc @krusche @thilo-behnke
