### ISSUE TITLE
Required and found mixed up in error log

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [ls1intum/ArTEMiS#375]
If there is a compilation error due to a wrong constructor, "required" and "found" are in reverse order. 

In this case the constructor was (String, String, int) and not (). Got me really confused until I switched from (String, String, Date) to (String, String, int) while I thought there was some syntax error on my side and could finally conclude that a change in the requirements does not make any sense. 
![Снимок экрана 2019-04-30 в 12 29 27](https://user-images.githubusercontent.com/20713070/56956350-2db07d00-6b44-11e9-98ce-8e799f931575.png)

**Comment by jpbernius** [comment]
This issue is related to an EIST exercise and **not** the ArTEMiS Platform. Please report problems regarding the exercises with the [exercise instructors](http://ase.in.tum.de/eist).

**Comment by krusche** [comment]
It is actually part of Artemis, because the test depends on the template tests, I will fix this as soon as possible.

**Comment by krusche** [comment]
@13XxM1CHA3lxX37 The test case is correct, the problem is the interpretation of the error message which actually comes from the Java compiler in this case, so we cannot really change it. 

You implemented a constructor with 3 arguments in the Student class. Our test case assumes the default constructor without arguments. The default constructor is only available automatically in Java, when there is no other constructor. If you add another constructor (as in your case), Java cannot invoke `Student student = new Student()` as it is specified in our test case. The Java compiler now assumes that the implementation of Student is correct (there are no errors), and it assumes the invocation of the constructor in our test case `InstantiationTest.java` is incorrect, because the test case uses a constructor that is not available.

I agree that the feedback is confusing, so we should try to catch such cases in the future and provide feedback that is easier to understand!
