### ISSUE TITLE
Load old build logs does not work

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#3849]
### Describe the bug

Loading old build failed results (build logs) depends on the participation id, therefore it is not possible to load build logs for an old submission.

### To Reproduce

1. Participate in a programming exercise multiple times with one build failed and one non build failed submission/result
2. Try to open the build failed result in the history (student or instructor view)
3. Notice that it won't work with an exception

### Expected behavior

It should also work for old results.
The REST call needs to be changed to depend on the result id (or submission id) and not on the participation id.

### What browsers are you seeing the problem on?

Chrome

**Comment by MaisiKoleni** [comment]
Requires small server code change here:
https://github.com/ls1intum/Artemis/blob/cdfe52901a486367757eba4d341cba572cc1141d/src/main/java/de/tum/in/www1/artemis/web/rest/repository/RepositoryProgrammingExerciseParticipationResource.java#L328-L335

On the client-side, however, a change would be more involved: The build output component only knows the participation and listens for build and result changes, and does not specify anything on it's own:
https://github.com/ls1intum/Artemis/blob/cdfe52901a486367757eba4d341cba572cc1141d/src/main/webapp/app/exercises/programming/shared/code-editor/build-output/code-editor-build-output.component.ts#L184-L203

The service uses the participation ID extracted from the URL path:
https://github.com/ls1intum/Artemis/blob/cdfe52901a486367757eba4d341cba572cc1141d/src/main/webapp/app/exercises/programming/shared/code-editor/service/code-editor-repository.service.ts#L115-L128

How would we like to handle that in the future? The client code makes it look like we don't always have a submission (but I would doubt results without submission can exist in Artemis). We could add an optional result/submission parameter to the service:
https://github.com/ls1intum/Artemis/blob/cdfe52901a486367757eba4d341cba572cc1141d/src/main/webapp/app/exercises/programming/shared/service/build-log.service.ts#L18-L24

And then add that to the code editor as an optional parameter as well. If not specified, we get the logs for the latest submission. Otherwise, we might need more work to make sure we always know the submission/result.

What solution would you have?
- A bigger refactoring to result/submission ID including the removal of the URL dependent service
- A small change by adding an optional result/submission ID, which would still be compatible with most of the code in its current state and less potential to create errors in new edge cases?

**Comment by krusche** [comment]
Build failed can only happen if there is a result and submission.
We could either use the `resultId` or `submissionId` to ask the server.
While the build logs are attached to a submission, it might make more sense the use the result, because one submission could have multiple results. Let's assume we have one submission with two results

Result 1: build failed
Result 2: 5 of 7 tests fail

Then, the user should only get the build logs, when he/she clicks on the first result, even though the build logs are attached to the programming submission (we decided this earlier to keep results exercise independent)

We should also check what happens if the same submission gets two "build failed" results. Are the old build logs overridden or are there suddenly two sets of build logs?

(however these are edge cases that we could also solve in a follow-up)

Regarding your question: I don't think we can get rid of the participation id in the build log service (it should still be part of the REST URL), so I think it makes more sense to add optional values for submissionId and/or resultId into the `domain`. It might also make sense to use a different name for `domain` because the term is very generic.

So this would rather be the proposed solution `a small change`.

**Comment by MaisiKoleni** [comment]
I looked it up and both logs and the build failed flag are overridden for each new result, so we only have such information for the latest result of a submission.
But I will have a look how this is communicated to the user.
