### ISSUE TITLE
Exam Mode: Students get confused because of wrong status in Artemis

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3901]
### Describe the bug

Multiple students reported that they got the message (on the exam page) after the exam is finished that they did not submitted their tasks.

This is actually wrong (I've checked that in the Score View)

![image](https://user-images.githubusercontent.com/22198798/129003069-828185c6-fe25-47f7-9b2e-721122ff1694.png)

This text could make the students feel unsecure about their actual participation

### To Reproduce

Unknown

### Expected behavior

Actually, the system shall show the correct state to the students

### What browsers are you seeing the problem on?

Firefox

**Comment by FlorianGlombik** [comment]
We have recently had a problem with programming exercises in the exam overview - the problem was related to the state of the exercise (active/inactive/finished/...) - since this is a programming exercise it might be related, you might want to have another look at the scores page and double-check whether the states of correctly displayed programming exercises matches the states of not correctly displayed exercises.

**Comment by dfuchss** [comment]
Thanks for the information. We are using v5.1.0 (since I didn't update the platform during exams) . I'll have a look at it

**Comment by dfuchss** [comment]
I think the issue is exactly that what you describe in #3855 .. therefore I think I may have to update Artemis ..

**Comment by dfuchss** [comment]
Currently I wait for the feedback of our students whether the update resolved the issue.

**Comment by dfuchss** [comment]
The issue is resolved by updating to the current artemis version :) Thanks for the help!
