### ISSUE TITLE
Modeling Exercise Export Example Solution Broken

### ISSUE THREAD

**Issue by FlorianGlombik** [ls1intum/Artemis#3997]
### Describe the bug

When using the export example solution functionality for modeling exercises this does not work.

### To Reproduce

1. Login as editor / instructor
2. Create a modeling exercise with an example solution
3. Open the exercise view of the created modeling exercise
4. Export the example solution
5. See that an error is displayed

### Expected behavior

The example solution should be exported, probably as JSON file that can be imported in Apollon.

### Screenshots

Error message displayed in the UI:
![image](https://user-images.githubusercontent.com/63976129/133241449-4c536a98-6cc6-458f-bedf-592880df8ddc.png)

Screencast:
![ExportModelingExampleSolutionBroken](https://user-images.githubusercontent.com/63976129/133242197-8622dc23-d620-4213-9006-54e185371491.gif)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output
```
Request URL: https://artemistest.ase.in.tum.de/api/apollon-convert/pdf
Request Method: POST
Status Code: 405 
```

**Comment by imstreetspirit** [comment]
Ok, I just tested this problem locally. Actually, it works on TS2. And I checked the feature implementation: https://github.com/ls1intum/Artemis/pull/3062. The feature has been tested on TS2. I think this related with active profiles on the server. This bug is reported on TS1. Because, when I add "apollon" in the active profiles in server configuration, api request has been reached to the server side. I do not think this is a bug.
