### ISSUE TITLE
🚀 Expose event API for third party apps

### ISSUE THREAD

**Issue by IgnusG** [ls1intum/ArTEMiS#423]
### Is your feature request related to a problem?
Some students cannot attend the lecture and don’t watch the stream but want to participate during the quizzes. 

### Describe the solution you'd like
Expose an API for events such as quiz ABC started - quiz ABC ended. This would allow to create a slack app for example which would post these notifications to an appropriate channel. 

I presume an API will be on the roadmap at some point. This is one of the example applications for it.

**Comment by krusche** [comment]
While we certainly want to notify students about certain events, such as new assessment results for their submission, I think exposing events to external applications is out of scope and might also be a privacy issue.

**Comment by IgnusG** [comment]
Btw. I heard comparisons with other similar tools being used as arguments for implementing/discarding certain features, so here are the 2 cents from moodle as an example https://docs.moodle.org/dev/Core_APIs

**Comment by krusche** [comment]
Who said that? The idea of Artemis is not to reimplement Moodle. We have a specific focus on delivering a modern web platform for interactive learning that provides (semi-
) automated feedback that is fair and helps in the learning process. Offering an API is nice to have, but currently we are facing many other more important issues.
By the way: if you miss a quiz, because you don’t want to follow the lecture (for whatever reason), you can still participate in the practice mode afterwards.
