### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by 16flotho** [ls1intum/Artemis#4404]
### Is your feature request related to a problem?

Me, everytime I open Artemis:
![cat-blind-flashbang-light-mode](https://user-images.githubusercontent.com/55878563/144045442-c6c3cb91-e6be-4c16-b132-9053814bd20a.gif)

### Describe the solution you'd like

Add Darkmode support

**Comment by Strohgelaender** [comment]
There are some workarounds to get a darkmode on your own:

1. DarkReader
You can use the browser extension [Dark Reader](https://darkreader.org/) to get dark mode not only on Artemis, but also on every other website.

2. Darkthemis
[This](https://userstyles.org/styles/176801/artemis-dark-mode) is a dark mode created by a student. Since I don't use it personally I cannot tell how well it's maintained and if it works correctly on every page. But you can still try it out.

**Comment by krusche** [comment]
Status update: @coaxial1 will look into this highly requested usability improvement in the near future. Santa might have a dark mode present for you ;-)

**Comment by LadnerJonas** [comment]
In the meantime, there is a student-created Browserextension:
https://github.com/Attednev/ArtemisDarkMode

**Comment by krusche** [comment]
We are still working on this issue. We expect a release in the next 4-6 weeks

**Comment by bassner** [comment]
The new dark mode has been merged and will be available on the production systems soon! 🎉 

Note that the feature is flagged as experimental, so please let us know if you guys run into any issues while using it! :)
