### ISSUE TITLE
"Go to repository" link on assessment page contains student username

### ISSUE THREAD

**Issue by timschumi** [ls1intum/Artemis#4489]
### Describe the bug

When assessing a programming exercise, the "Go to repository" link will use the student username for authentication rather than the username of the person that is currently logged in (or preferably, none). This is annoying when clicking on or copying the link to that Git repository, since the tutor isn't able to authenticate as the user.

### To Reproduce

1. Go to '[https://artemis.ase.in.tum.de/course-management/155/programming-exercises/5412/submissions/3413469/assessment](https://artemis.ase.in.tum.de/course-management/155/programming-exercises/5412/submissions/3413469/assessment)'
2. Click on 'Go to repository' or right-click to copy the link
3. Observe that the link has `<student username>@` prepended.

### Expected behavior

The link should either be prepended with the username of the currently logged in user or none at all.

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
Thanks for the bug report, this is tricky to reproduce, because it only happens for tutors. I was not able to reproduce the issue on Safari and Chrome with my admin account. When I open the page that you link and click on the Go to repository, then it opens without `<student username>@` prepended.

I also looked up the source code and even debugged the code on the production system: it correctly computes a `userIndependentRepositoryUrl` that is used for the go to repository link.

I guess the issue is in the implementation of `addUserIndependentRepositoryUrl(participation: ProgrammingExerciseStudentParticipation)` in `participation.utils.ts`. It assumes that the student login is available, however due to the double blind review procedure, we recently remove this on the server.

I think we should compute `userIndependentRepositoryUrl` on the server to avoid this issue.

**Comment by timschumi** [comment]
This is interesting.

When hovering over the link, it correctly shows as bare URL without any username. When right-clicking and selecting "Inspect element", the `href` attribute clearly shows a URL that includes the student username.

Chrome (correctly?) opens the no-username URL when just clicking on the link. When right-clicking and selecting "Copy link address" it will place the URL including the username into the clipboard.

Firefox uses the URL that includes the username both when clicking the link as well as when pressing "Copy link address".

I can only assume that there is some non-standard JavaScript that is happening here.

**Comment by timschumi** [comment]
I might have an idea why the `addUserIndependentRepositoryUrl` method does not work as expected:

![Bildschirmfoto_2021-12-10_16-52-22](https://user-images.githubusercontent.com/16820960/145604512-a30bfd96-7d1f-4a29-a770-aaa23321881e.png)

Are we omitting student information by accident on less-privileged accounts? I can't spot any student data in the matching API reponse either ([https://artemis.ase.in.tum.de/api/programming-submissions/3413469/lock](https://artemis.ase.in.tum.de/api/programming-submissions/3413469/lock)), but the content of that response seems to match what is set in the object down the line.
