### ISSUE TITLE
Allow the students to open the Programming Editor after Assessment

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#4614]
### Is your feature request related to a problem?

Students have no link to open the Programming Editor after the manual assessment is finished. Therefore, it is hard for them to map the comments of tutors to the actual position in the code. 

The main functionality is already present (only the link on the student view is missing after the assessment due date):
Needed Link: `https://artemis.../courses/{courseId}/programming-exercises/{exId}/code-editor/{participationId}`
![image](https://user-images.githubusercontent.com/22198798/149782634-bee3caad-ed73-4a01-a21c-acd4ab0d40a8.png)

There is no button in the exercise view of the Task:
![image](https://user-images.githubusercontent.com/22198798/149782788-46f4da7e-ced2-4844-b61e-ff911b123d01.png)

### Describe the solution you'd like

Add a button to the student's view that allows it to open the programming editor in Artemis (if activated for the task).

**Comment by krusche** [comment]
This is more a bug than a feature, because this has been working already.
It seems the reason is that the button is not displayed after the due date and/or when the participation is inactive.
This should not be the case. Students should always be able to see their code in the online code editor (potentially read-only after the deadline) when the code editor is active.

I assume the logic for displaying the button "Open Online Code Editor" is wrong at the moment.

**Comment by coaxial1** [comment]
Could you check if https://github.com/ls1intum/Artemis/pull/4643/ solves your issue?

**Comment by dfuchss** [comment]
I'll test it later asap.

**Comment by dfuchss** [comment]
I'll close since #4643 is merged :)
