### ISSUE TITLE
Increase Complaint Text Limit

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#4664]
### Is your feature request related to a problem?

Our teaching assistants and students have requested that the limit for complaints and complaint feedback be increased.

### Describe the solution you'd like

Increase the limit of characters for complaints and feedback.

### Additional context

@krusche according to out TAs this feature / configuration would be very important since they had to use some external tools (e.g., etherpad) to provide the feedback to the students in the level of detail which was needed.

**Comment by krusche** [comment]
The limit is on purpose so that students keep themselves short. Instructors in large courses typically do not have time to read many very long complaints.

If there is an obvious mistake, students can describe it shortly. If a long discussion is needed, just to get 0.5 more points for an exercise with 20 points, the effort needed for the discussion is simply not justified.

Complaint responses could theoretically be longer, but I also suggest that instructors do not spend too much time on it!

We could make the limit configurable for the instructor of the course, but we don't have capacities to work on this, so someone in your team would need to implement this.

**Comment by dfuchss** [comment]
@krusche I think at least for exams we need the ability to have more text in the complaints. This term, we got many text that contains something like "the 5000 characters are not enough, I send a mail". Therefore, I would suggest to handle at least exams different since they are relevant for grades.

**Comment by krusche** [comment]
We never had such a case. I suggest to ignore such emails

**Comment by krusche** [comment]
Other exam systems at TUM use even shorter limits for complaints than Artemis does, but if you really want to handle such long complaints, we probably need to change from varchar to longtext. The actual complaint length is already configurable in the course.

**Comment by dfuchss** [comment]
Yes, but as far as I remember; the complaints still have a maximum length of 5000 chars

**Comment by Shirkanesi** [comment]
> need to change from varchar to longtext

Sounds like a reasonable solution :)
If in addition to the change in the database also the constant in the code (https://github.com/ls1intum/Artemis/blob/a0347b692c9eb247aed8a41bb51a25d8f51d24a2/src/main/java/de/tum/in/www1/artemis/config/Constants.java#L124) will get configurable, it is easy for instructors to tweak their limitations to their liking.

> Other exam systems at TUM use even shorter limits for complaints than Artemis does

I think just because it works for a specific case at TUM means, it will work the same everywhere else ;-)

**Comment by krusche** [comment]
> > Other exam systems at TUM use even shorter limits for complaints than Artemis does
> 
> 
> 
> I think just because it works for a specific case at TUM means, it will work the same everywhere else ;-)
> 
> 

You are completely right, I just wanted to reflect that there is no actual legal reason to increase it. If you would like to support extremely long complaints, please go ahead and implement the change
