### ISSUE TITLE
Importing students into a course is failing

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#4939]
### Describe the bug

Importing students from the Tum Online CSV file is not possible. 

### To Reproduce

1. Go to any course
2. Click on import students 
3. Select the CSV file 
4. Check that you have a file with the total number of students
5. Import it and check if you get a message at the end of the dialogue that says Not found: # students 

### Expected behavior

Should be import it the list of students

### Screenshots

<img width="789" alt="image" src="https://user-images.githubusercontent.com/88991954/164212239-a0ef26db-a800-41c4-89e0-a5726115a942.png">

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
I think there is an issue with the used CSV file, the header name is different and there seems to be a bug in Artemis if the header name is not correct. The tooltip explains it

<img width="217" alt="image" src="https://user-images.githubusercontent.com/744067/164733863-c812d8ba-2a32-477f-839b-facb109483c5.png">

We will try to make the import more generic so that it is compatible with more spellings of login/username (German and English) and registration number / matriculation number (German and English) and different kinds of first and last names

Additional improvement: All "not found" lines should be red, not only every second one

**Comment by krusche** [comment]
another issue was that the provide file included registration numbers with a leading ' '
I will use `trim()` now to avoid issues in such cases

**Comment by krusche** [comment]
Fixed in b054013ff172ee355d41e1fe6c11e474cffaa62e
