### ISSUE TITLE
Exam: Students Can File Complaints for Text Exercises Before the Review Period

### ISSUE THREAD

**Issue by michael-schwarz** [ls1intum/Artemis#4984]
### Describe the bug

In exams, it seems that students can file complaints for text exercises as soon as the results are published, even if the review period has not begun. For programming exercises, it seems to work as expected.

This is not a major problem, it is just strange that it works differently than expected.

### To Reproduce

1. Conduct an exam, grade it.
2. Set the result publication date, and set the review period to only start later
3. Once the results are published, from student view you can file complaints for text exercises (even though the review period has not started)

### Expected behavior

Students can only file complaints for text exercises once the review period started.

### What browsers are you seeing the problem on?

Chrome

### Additional context

To see the problem in action, one (w/ admin access to the TUM instance) can currently observe it on the FPV exam (course No. 182) before the start of the review period today at 1:30pm.

**Comment by mallgaier** [comment]
This affects Text- / Modelling- and File-Upload Exercises. 

The complaint component is wrongly shown on the results - subpage of the exercise. Here, the complaint can be filed at any time because the complaint-component doesn't receive the exam information and thus cannot determine the student review period. The corresponding text-/modelling-/file-upload component also has no exam information.

Thus, the complaint component is displayed, as for normal course exercises, after the assessment due date, which is independent of the exam review period. That's also the reason the wrong hint with the limited number of complaints is shown to the student.

With the PR #4988 the complaint component is hidden for exam exercises and students can use the indented way to complain about an exam exercise - via the exam summary page and within the student review window.
