### ISSUE TITLE
Quiz Answer Matching Options UI-Layout Not Clear

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#5000]
### Is your feature request related to a problem?

When creating short answer quiz exercises, it is not obvious what the percent slider is used for.
![Screenshot 2022-05-02 at 13-26-56 Quiz Exercises](https://user-images.githubusercontent.com/64250573/166226722-5f415672-5739-407d-80ae-ab2408e4aac2.png)

It is also not clear that the two checkboxes beside it affect the same underlying option about matching the answer text.

### Describe the solution you'd like

I’d like the two checkboxes and the slider to receive some kind of common heading in the style of ‘Scoring Type’.
Additionally, the two checkboxes and the slider should be visually grouped together to make more obvious that they are part of the same setting.

**Comment by Rocketman112** [comment]
For a possible solution, could we provide a header similar to the "scoring type" and put a box around the two checkboxes and the slider bar?

**Comment by Rocketman112** [comment]
Also is there a specific header that anyone had in mind for this issue?

**Comment by jgrant12345** [comment]
For a possible solution, could we provide a header similar to the "scoring type" and put a box around the two checkboxes and the slider bar?

**Comment by jgrant12345** [comment]
Is there a specific header that you had in mind to group these issue?

**Comment by b-fein** [comment]
A header like ‘Scoring Type’ is probably the best option. I have no specific preference, but I think ‘Answer Matching’ would make sense. I have no great idea for the German version (yet).

Maybe reversing the order of the three elements to be like slider, match exactly, match letter case would be enough. Then the title is directly next to the slider and for the other two options it should be clear that they are also part of the matching options from their text.
That’s just an idea, one probably has to actually implement it and look at it to decide if that is enough or if some kind of box or placing the three options on a separate line beneath Scoring Type is necessary.

**Comment by sunsetcoder** [comment]
![image](https://user-images.githubusercontent.com/33063132/167267100-710493c5-9575-4e78-b590-252920562084.png)

Solution 1:
- The "match answers exactly" checkbox and slider for similarity value are within their own div with a border, heading "Answer Matching" since these two options are mutually exclusive and unrelated to "Match Letter Case". When the user selects a 100% similarity value, "Match Answers Exactly" is automatically checked, and it is consistent with the HTML code since these two are within their own "match-percentage-container", seperate from "Match Letter Case".

**Comment by sunsetcoder** [comment]
![image](https://user-images.githubusercontent.com/33063132/167267279-5f1e08e5-bbc2-41b7-87fe-a0bb34554a66.png)

reversing the order of the three elements to be like slider, match exactly, match letter case so that the slider is directly next to "Scoring Type" dropdown box.  
Would you prefer "Match letter case" to be on the next line below the dropdown box?

**Comment by b-fein** [comment]
Thanks, the solution as shown in the screenshot in #5051 looks good. :+1: 

Although, I’m not sure if the box around the options is really needed, as I think that the new title provides enough of a separation and explanation to visually group the three elements. (That’s maybe personal preference, tough, and you can keep it if you think it is better with the box.)
