### ISSUE TITLE
Delete exercise does not work in case plagiarism cases exist

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#5759]
### Describe the bug

When you delete an exercise (e.g. in an exam) for which plagiarism cases (potentially with posts) exist, the deletion does not work due to database constraints.

### To Reproduce

1. Create a text exercise with 2 larger identical submissions
2. Run plagiarism checks and accept the found plagiarism
3. Make sure a plagiarism case was created
4. Delete the exercise --> Internal Server Error

### Expected behavior

Deleting the exercise in such a case should be possible.
All associated plagiarism cases (and posts) should be delete beforehand

### What browsers are you seeing the problem on?

Chrome

**Comment by jakubriegel** [comment]
@krusche I'm not able to reproduce this anymore. Here is the video with the flow I follow: https://www.loom.com/share/ab028925577d4bb394ede1326edd74d6.

1. Do I follow the correct flow?
1. If yes: Do you agree that the issue is solved by now?
1. If no: What should I perform to reproduce that?

**Comment by jakubriegel** [comment]
The flow seems correct.

Entities related to plagiarism get deleted by cascading:
- the server deletes `PlagiarismResult` first. This by cascading removes `PlagiarismComparison`:
   - https://github.com/ls1intum/Artemis/blob/9504ec832d1e81cf6e4afb0b61369ba575cedce1/src/main/java/de/tum/in/www1/artemis/service/ExerciseDeletionService.java#L139
   - https://github.com/ls1intum/Artemis/blob/9504ec832d1e81cf6e4afb0b61369ba575cedce1/src/main/java/de/tum/in/www1/artemis/domain/plagiarism/PlagiarismResult.java#L35
- then the server removes the `Exercise` which by cascading removes all `PlagiarismCase`:
   - https://github.com/ls1intum/Artemis/blob/9504ec832d1e81cf6e4afb0b61369ba575cedce1/src/main/java/de/tum/in/www1/artemis/service/ExerciseDeletionService.java#L139
   - https://github.com/ls1intum/Artemis/blob/9504ec832d1e81cf6e4afb0b61369ba575cedce1/src/main/java/de/tum/in/www1/artemis/domain/Exercise.java#L138


Interestingly, neither of those lines was edited after this issue was created. But, manual testing and code analysis show that the anticipated flow works.
