### ISSUE TITLE
Missing Exercise in Statistics

### ISSUE THREAD

**Issue by JoejoeSt** [ls1intum/Artemis#581]
### Describe the bug
Even though the exercise H05E02 has a grading in the statistics page, there is no grading on the course main page or the view submission page. Reloading doesn't resolve this problem.

#### Screenshots
![1](https://user-images.githubusercontent.com/38322605/59520847-28787900-8ecb-11e9-9987-f4cc544297aa.PNG)
![2](https://user-images.githubusercontent.com/38322605/59520851-2a423c80-8ecb-11e9-841e-bc93e74f16a3.PNG)

### Environment

<details><pre>
 - OS 1: Windows 10
 - Browser 1: Firefox
 - OS 2: MacOs X High Sierra
 - Browser 2: Safari
</pre></details>

**Comment by krusche** [comment]
Thanks for reporting this problem. The exercise is graded, but the grade is not yet released, so that the tutors could still override it until all other assessments have been made. We release the grades when the deadline for the assessment due date has been reached. 

Therefore the result for H05E02 should not be visible in the statistics page.

@maximilianmeier @SiggZ @rpadovani could you please have a look why the result is already shown in the statistics page? It should not even be available on the client and it should be filtered out on the server. Thanks!

**Comment by maximilianmeier** [comment]
We improved the statistics view in #590.
With that we fixed issues that the score of exercises were displayed wrong
