### ISSUE TITLE
`Exam programming exercises`: Students cannot review their own code for submitted exercises

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#5877]
### Describe the bug

Related to #5876

Users cannot see their own code after the exam ended. Therefore, the review is difficult.

Possibly only happens for test exams.

Important, as reviewing their own code after receiving feedback does not seem to be possible from within Artemis currently (→ https://github.com/ls1intum/Artemis/issues/5025, https://github.com/ls1intum/Artemis/issues/3031).

### To Reproduce

Same steps as in #5876. Then,

1. On the summary page there is a link to the GitLab repo.
2. The link does not work as the user is not a member of the repository.

### Expected behavior

The student is a member of the repository with read-only rights (reporter).

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
I think they can simply look into the repository in the version control system

**Comment by b-fein** [comment]
At least for text exams that is not the case in GitLab setups as they are not a member of the repository, therefore the link in the summary results in a 403-Access-Forbidden.

**Comment by krusche** [comment]
Ok, then we should fix it. I think they definitely get read permissions for the repository when the exam starts:

**Exam start:**
* Only online code editor: add read permission
* All other configurations: add read and write permissions

**Exam end:**
* Only online code editor: nothing to be done
* All other configurations: remove write permission

One question remains: Should we support that an instructor can change this during the exam? Then we would need to add / remove write permissions as implemented for course exercises, which would theoretically be possible, but not really feasible in terms of user interface because the students would need to reload the exam mode page (and enter the exam again on the start page)
