### ISSUE TITLE
`Learning Goals`: Use additional metrics for confidence score

### ISSUE THREAD

**Issue by ge65cer** [ls1intum/Artemis#6084]
### Is your feature request related to a problem?

We currently use an adaptive learning system that uses descriptive analytics as an input.
These are for example the student's score in exercises compared to their peers, the progress in lecture units or the mastered learning goals.

### Describe the solution you'd like

We imagine that even more metrics could be used for estimating the mastery in a competency and the adaption process.
The number of submissions for an exercise might be a good indicator of how comfortably a student can use their knowledge.
Requiring multiple attempts or feedback-loops to pass an exercise might indicate that the student is struggling with the difficulty of the task.
Expertise in an area could be measured by the working time needed for an exercise.
A student comfortable with the material will certainly be able to answer a problem faster than someone first looking up the questioned concepts in the lecture slides.

**Comment by julian-christl** [comment]
This, however, can cause follow-up issues:
- What if you have two people: Person A confidently solving the exercise but perfecting everything because they want to (e.g. improving phrasing of text exercises, improving code structure, etc while they actually already solved the exercise, vs. Person B that takes longer but is happy with the simplest solution. Both might take similar time
- What if you have a person that starts the exercise but then has to go somewhere and leave it? The clock is ticking, but that doesn't say anything about their confidence but only about their time schedule.
- The number of submissions can also be caused by issues with the problem statement/the build. E.g. a student tries different approaches until they are confident that there must be an issue, and they ask their instructor. The instructor then checks the report and confirms the issue. But now the student had many submissions while maybe actually solving it first try.
- ... I'm sure there are other causes why someone takes

Not trying to be destructive ^^
