### ISSUE TITLE
`Plagiarism Checks`: It is not possible to deny a plagiarism case if the same student was involved in another case and this was marked as `confirm`

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#6528]
### Describe the bug

 It is not possible to deny a plagiarism case if the same student was involved in another case and this was marked as `confirm`

### To Reproduce

1. Run a plagiarism check with an exercise. 
2. Look for cases that involve the same student.
3. Confirm one of this 
4. Try to deny another case where the same student is involved. 
5. Verify you get the same error message as the screencast

### Expected behavior

Should be possible to deny a plagiarism case if the same student was involved in another case and this was marked as `confirm`. 

### Screenshots

https://user-images.githubusercontent.com/88991954/236160753-fcd28077-92ee-4661-94db-4b7d292f9d78.mov

### Which version of Artemis are you seeing the problem on?

6.1.5

### What browsers are you seeing the problem on?

Chrome

**Comment by jakubriegel** [comment]
I'll work on that

**Comment by jakubriegel** [comment]
Cannot reproduce that. Loom with my steps: https://www.loom.com/share/16273a27f1d1431bb2185f13d0cc8f95

Can you verify that this still occurs?

**Comment by jakubriegel** [comment]
This issue and #6529 are caused by double `PlagiarismCase` row for the student `ge32tog `. Those were created most likely due to concurrent access to the db as two tutors were reviewing submissions. 

**Quick fix:** manually delete one of `PlagiarismCase`s and then delete second by clicking `Deny` on plagiarism checks.

**Actual fix:** to be discussed; maybe introduce locking? or maybe this was a corner case we don't need to cover?

Tech note:
-  `PlagiarismCase` is created only in this line https://github.com/ls1intum/Artemis/blob/develop/src/main/java/de/tum/in/www1/artemis/service/plagiarism/PlagiarismService.java#L69, which is triggered only in the flow of plagiarism detection review

**Comment by jakubriegel** [comment]
See https://github.com/ls1intum/Artemis/issues/6529
