### ISSUE TITLE
`Programming Exercises`, `Manual Assessment`: Unsaved Inline Annotation Broken when Switching Files

### ISSUE THREAD

**Issue by chrisknedl** [ls1intum/Artemis#6678]
### Describe the bug

In the assessment view, inline annotations that are not saved might break when switching files in the online editor.
They can no longer be saved or cancelled.
Edit: At one occasion, one of the tutor comments could not be edited anymore (6.2.0). This can also be reproduced by switching between the files, as explained in the section below.

### To Reproduce

1. Navigate to the assessment view of any submission.
2. Open the inline annotation for any file and keep it open without saving it.
3. Switch to another file and do the same thing.
4. After repeating this a few times, it is possible that the `Cancel` and `Save` buttons of the inline annotation editor don't work anymore.

### Expected behavior

I'd expect that switching between files in the editor doesn't affect the inline comments and I can continue working where I left off.

### Screenshots

<img width="1728" alt="Bildschirmfoto 2023-06-06 um 20 09 28" src="https://github.com/ls1intum/Artemis/assets/53149143/105cf8aa-97c7-460e-8ae3-9cf9ac38a792">

### Which version of Artemis are you seeing the problem on?

6.2.0 & 6.2.2 & 6.3.1 (other ones not tested)

### What browsers are you seeing the problem on?

Chrome

**Comment by b-fein** [comment]
Another error report from an instructor:

Happened directly when writing a comment. Comment got stuck open, cancel/save do not work any more.

**Comment by bassner** [comment]
Anything in the console?

**Comment by b-fein** [comment]
(Ah forgot that information)
I asked them to please explicitly check after it happened for the first time, but apparently no console output.

**Comment by krusche** [comment]
maybe automatic change tracking in Angular is going crazy? Could you check if the html of the involved components invoke methods? Or if the inputs of the involved components involve method calls?
Another issue could be some kind of dead lock in the involved rxjs code

**Comment by chbachm** [comment]
A potentially related report from another instructor: I clicked on a line's + sign and got displayed an inline comment box from another class, see screenshot. This is the Interface, and I did not create the comment here, but definitely belongs to another class.

![assessment](https://github.com/ls1intum/Artemis/assets/124778808/7e17d8ef-6467-4e46-bb8a-7116e81411bc)

Unfortuantely, we have no idea how to track these issues down or debug that. It is even difficult to tirgger this issues on demand for debugging. On the other side while doing real assements they show up quite frequently, we have one instructur say twice an hour. Again nothing in console or Sentry. I hope that comments are not shown at wrong places to students.

**Comment by b-fein** [comment]
In case a student submission a a long feedback, and the tutor opens the result details, there probably is a cyclic dependency between the longFeedback and the feedback. Therefore, a following save/submit has an issue which in turn causes the rest of the Javascript runtime to no longer continue properly.

**Comment by b-fein** [comment]
I think we can narrow down the issue to what happens inside 
https://github.com/ls1intum/Artemis/blob/83ae671d4b0123c59fa86f658c50d800091ef78e/src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-inline-feedback.component.ts

The components gets the valid feedback object and the attributes all seem correct when logging them as part of an `ngOnInit` method.

At that point I‘m not sure where inside the Angular component initialisation it could go wrong. **Any help from someone with more experience in that area would be very much appreciated.**

It seems that in most cases only the `@Output` events for the button presses are broken since the component no longer reacts to button presses.
IIRC in some cases, though, not even the text area was populated with the correct data which would indicate that the initialisation of the components broke before even before that (?).

**Comment by chbachm** [comment]
Right, in most case many existing inline comments are shown openend with an empty text area. Empty means it shows the initial help text "You can enter feedback here...", like they are freshly added after clicking on a line's +. And then all are blocked, i.e., the buttons save, abort, ... do not work. The buttons' listener methods are not called, i.e., a break point with them is not reached after clicking on such a button.

The issue is triggerable, however, it may last say up to 15 min of clicking, i,e,, creating and editing inline comments in different files of an assessment and maybe inspecting the feedback from time to time. But the issue may also appear sometimes quickly.  As far as I can say it nearly always shows up immediately after a file switch. The only thing what helps then is a base reload of the page, then all existing comments are shown closed with an operable edit button as the should.

**Comment by krusche** [comment]
Sounds like some objects do not get cleaned up properly. Could this be an issue?
