### ISSUE TITLE
Liquibase migration script not working with postgres

### ISSUE THREAD

**Issue by frederik-kt** [ls1intum/Artemis#6761]
### Describe the bug

The liquibase migration script changeset with id `20230510004600` does not work for a setup with Postgres.
When starting Artemis with a connection to the Postgres database, the error `org.postgresql.util.PSQLException: ERROR: column "participation" of relation "participation" does not exist` is shown.

### To Reproduce

1. Start Artemis with the Postgres database configured.

### Expected behavior

The migration script should run fine for Postgres the same way it does for MySQL.

### Which version of Artemis are you seeing the problem on?

6.3.1

### What browsers are you seeing the problem on?

Chrome

**Comment by b-fein** [comment]
Part of the problem can be fixed by removing the `participation.` prefix from the `SET` clause, i.e.
```sql
UPDATE participation
SET locked = TRUE
WHERE …
```

---

However, the `TIMEADD` function is specific to MySQL. I tried a few variants of standard-SQL
```sql
exercise.start_date + INTERVAL … SECOND
```
instead, but could not find a way that works in both databases.

What could maybe work is to interpret `exercise.start_date` as unix-seconds-timestamp, add the `student_exam.working_time` and convert it back into a full timestamp.
