### ISSUE TITLE
everything goes kabooom if you add a binary in template/solution repository

### ISSUE THREAD

**Issue by rcastellotti** [ls1intum/Artemis#6890]
### Describe the bug

it is impossible to add a binary to a repository on bitbucket and then import the exercise in an exam. We (EIST team) changed the exercise so we don't have a binary on bitbucket but I think you should investigate this as we lost a lot of time trying to understand what was wrong.

MRE
Exercise: https://artemis.ase.in.tum.de/course-management/265/programming-exercises/10839
Repository: https://bitbucket.ase.in.tum.de/projects/EIST23TESTMREBREAKS/repos/eist23testmrebreaks-exercise/browse

### To Reproduce

.

### Expected behavior

.

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/43064224/e6266af4-e471-4f13-a881-fd2393d29481)

### Which version of Artemis are you seeing the problem on?

6.3.3

### What browsers are you seeing the problem on?

Chrome

**Comment by JohannesStoehr** [comment]
I tried to reproduce the issue and used a random binary file in the repositories on the top level, in the source folder and in an additional folder but was not able to get any issued from the consistency check or the import of that programming exercise.
We developers also don't have access to your course, so could you specify the problem here a bit more? E.g. where exactly was the binary in the repository located, can you include the binary file? Was it possible to import the exercise after deleting the binary in bitbucket?

**Comment by krusche** [comment]
It seems this only happens for Bitbucket and not for Gitlab. 
Also for start exercise, it sometimes works in the 2nd or 3rd attempt. Therefore, we assume it's a timing issue

We currently investigate potential workarounds such as a short wait between repository creation and the first push operation from Artemis using JGit
