### ISSUE TITLE
expand all button

### ISSUE THREAD

**Issue by klaudiapazdzierz** [ls1intum/Artemis#6928]
### Is your feature request related to a problem?

I really like Artemis but I'm always frustrated when I am looking for an exercise/slideset in a course and have to click on each date (e.g.  "2023-06-18 - 2023-06-24 (Exercises: 7)") in "Exercises" or "Lectures" to find it - sorting lectures/exercises according to date is nice, however, I don't remember when exactly each topic was covered so I have to click on several dates (it's annoying when preparing to exams).

### Describe the solution you'd like

expand all button

**Comment by florian-glombik** [comment]
Closing the issue since the issue appears to be addressed with the "new" in categories (`No Date`, `Past`, `Current`, `Up Next`) 

Additionally some filter logic will be added soon that should help with the exam preparation: [General: Add filter for exercises #8858](https://github.com/ls1intum/Artemis/pull/8858)
