### ISSUE TITLE
Exams: Students who get their repos unlocked last are disadvantaged timewise

### ISSUE THREAD

**Issue by pogobanane** [ls1intum/Artemis#6971]
### Describe the bug

Student repos are not unlocked all at the same time (due to high number of students and repos). Yet, their repos are closed all at the same time. Or more specifically, additional commits are marked as illegal actions, effectively closing submission deadline for all students at the same time. 

### To Reproduce

1. enter an exam as a student
2. attempt to check out a programming assingment
3. get permission denied, because your repo wasnt unlocked yet\
4. say 1min after exam start, your repo finally changes permissions
5. 1min after exam deadline: student should be allowed to push, because he could only start 1 min late

### Expected behavior

A similar behaviour as with paper exams: The one who receives his exam first has to hand it in first. This way everyone has an equal chance for working time. 

### Which version of Artemis are you seeing the problem on?

6.3.6

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

Browser: not needed for reproduction

The proposed change also fixes the issue of students knowingly or unknowingly pushing code solutions after the deadline, getting the entire task marked with "illegal submission" and getting graded 0 points for it. Without this change, course organisers receive more complaints and would have to **manually delete** the offending commits on an individual basis.

**Comment by pogobanane** [comment]
The issue mentioned in additional context should probably its own github issue.

**Comment by Strohgelaender** [comment]
Did you use the Prepare Exercises functionality before conducting the exam? Student repositories get unlocked 5 minutes before the exam starts, so all students should be able to start at the same time without any waiting time.

**Comment by krusche** [comment]
I think this only applies to exams with more than 2000 registered students with more than 4 programming exercises.
Artemis unlocks repositories at the beginning of the exam in up to 4 threads and locks them at the end of the exam in up to 4 threads. We could try to parallelize more, however this might lead to performance issues on the version control server (e.g. Bitbucket). In the TUM production instance, one thread unlocks around 10 repos per second, the lock operation at the end is a bit faster with around 13 repos per second.

When investigating the situation, I found that the following situation occurred during the test exams (with 7 programming exercises and ~2,300 participants --> in total 16,100 repositories):

For all students 4 out of 7 programming exercises have been unlocked at the exam start, so they could immediately start working on the majority of exercises. The other 3 exercises are unlocked until ~3min after exam start, so there is no big disadvantage given the 10min time for technical issues. Additionally, students typically read the problem statement before cloning the git repository, so chances are low that many students are affected by the issue.

There are multiple workarounds for this issue:
* Use a smaller amount of programming exercises in the exam
* When you have less participants in the final exam, it should become faster. Typically, not all students who participate in the course also register of the final exam
* Ask students to work on another programming exercise in case one repo should still be locked within the first few minutes

As @Strohgelaender pointed out, the situation at the end of the exam is different. Artemis tracks illegal submissions after the official deadline, in case students could still push their commit because the repo was not yet locked. 

An illegal submission would typically lead to 0 points, but theoretically, you can also go through those illegal submissions manually and reset them. However, I personally would not recommend this, because this would actually motivate students to try to push their commits after the official end of their exam. If at all, I would do this in cases the push was only a few seconds (e.g. < 3s) late and the commit date is clearly before the official deadline.

In any case, I would recommend to students to push their changes regularly and avoid pushing code in the last second, because this could lead to compile errors which might also lead to 0 points.

**Comment by krusche** [comment]
Right now, we cannot really improve this situation in a fair and consistent way, so I will close this issue
