### ISSUE TITLE
Using C programming exercises with Jenkins is broken

### ISSUE THREAD

**Issue by TheZoker** [ls1intum/Artemis#6994]
### Describe the bug

Currently when using Jenkins as the main CI and creating a programming exercise using C as the programming language does not work. Jenkins fails to compile it and does not respond with the result back to Artemis. 

### To Reproduce

1. Use for example TS2 (which used Jenkins as the CI)
2. Create a new programming exercise with C as the language
3. Go to the jenkins instance 
4. Inspect the CI run

### Expected behavior

Compile the programming language without issue or at least report the issue back to Artemis.

### Screenshots

No response to Artemis:
![image](https://github.com/ls1intum/Artemis/assets/1368405/19054960-8b50-4e54-ad2d-f96ba5eb185a)

All builds fail:
![image](https://github.com/ls1intum/Artemis/assets/1368405/10989678-e8f7-44e5-bbae-ee312eb0956d)

### Which version of Artemis are you seeing the problem on?

6.3.8

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by b-fein** [comment]
Related 2778

**Comment by b-fein** [comment]
Workaround until template is fixed:

https://gist.github.com/b-fein/114948708f1cb26e7bc958ea5d196397

- adapt pipeline definition in Artemis via the ‘Edit Build Plan’ button on the exercise details page.
- move all files in the `TEST` repository one level deeper into a new `tests/` directory.
  - NOTE: now some files like `tests/tests/....py` have to exist.
- remove the `requirements.txt` from the `TEST` repo since Debian no longer allows global `pip` package installs (there probably is some environment variable one can set to override that?)
