### ISSUE TITLE
Revoking permissions does not invalidate session keys

### ISSUE THREAD

**Issue by pogobanane** [ls1intum/Artemis#7024]
### Describe the bug

Changing permissions (e.g. give a user editor or instructor permissions to a course) requires the user to log out and back in for the changes to apply. 

This is problematic when revoking e.g. instructor or editor permissions from a user, since he can continue to edit with his existing stay-logged-in-login-session. 

### To Reproduce

.

### Expected behavior

.

### Which version of Artemis are you seeing the problem on?

6.3.8

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

**Comment by krusche** [comment]
The description of the issue is incorrect! Artemis has a two way authorization system. There is a global role, e.g. TA, EDITOR, INSTRUCTOR. This role is independent of courses and is encoded in the authorization token. It is used to quickly check if a user can do certain action in general (i.e. globally, not specific for a certain course). This check is fast and prevents user from doing certain actions if they are not an instructor in any course.

When a request passes this initial step, Artemis always checks if a user actually has the specified role (e.g. Instructor) in a course or not by querying the Artemis database. If you remove a user from the instructor group of a course, this check would immediately fail for the next request of this user.

In addition, when sending data from courses to the client, the server always takes care that only data is sent that the user is actually allowed to see based on the assigned courses

So the only inconvenience that exists at the moment is the following: 
- if a user receives a new global role for the first time, he/she must logout and login again to synchronize this
- if a user loses a global role (happens rarely), he/she must logout and login again to synchronize this

Both is not really a big issue and we decided to live with it, because there is not really a proper solution when using authorization tokens. The only user facing issue is that they do or not see the course management, even if they should or should not see it.

**Comment by pogobanane** [comment]
Ah ok. I now understand that logout/in is not required when losing permissions. That removes all criticality from this issue. 

Thanks for clarifying.
