### ISSUE TITLE
`Programming exercises`: Student repo download has nested zip-in-zip-file instead of only zipped repo

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#7732]
### Describe the bug

When manually assessing a programming exercise, there is a download button to download the student repository as zip file.

This zip file contains another zip file with the actual repository. It would be nice if there was only one zip to unpack.

### To Reproduce

Programming exercise with manual assessment and at least one assessable submission.

1. Assess the submission.
2. Use the ‘Download Repo’ button above the online editor.
3. Open the ZIP file locally. It has another ZIP file inside.

### Expected behavior

There is only one ZIP instead of a nested one.

### Which version of Artemis are you seeing the problem on?

6.7.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Firefox

**Comment by krusche** [comment]
I think there is a trade-off. If you have 2000 repos with many small files, having the nested structure can be helpful if you only need to unzip a few repos. Unzipping all repos without the nested structure would then take more time. I do not really use this feature on my own, so I do not have a strong opinion, but the implementation with the nested structure was intentional. We could still change it in the future.

**Comment by BaumiCoder** [comment]
My Pull Request would avoid nested zip files for this situation. If you only need a few repos, you can only unzip a subfolder of the zip archive. I think that should achieve a similar performance.
