### ISSUE TITLE
`Assessment`: Editing another tutor’s assessment shows ‘locked by null (null)’

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#7757]
### Describe the bug

When editing another tutor’s/instructor’s manual assessment, the UI shows which tutor/instructor created the original assessment. After editing/overriding the assessment, this text breaks.

### To Reproduce

1. As an instructor open a manual assessment owned by another tutor/instructor. It shows assessment is locked by the correct owner.
2. Change or add an (inline) feedback.
3. Override the assessment.
4. The name of locked by is now null (null).

### Expected behavior

The assessment locked by text is changed to `me` instead of `null`.

### Which version of Artemis are you seeing the problem on?

6.7.0

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional context

Tested only for programming exercises.

**Comment by kaancayli** [comment]
Hi, I'm working on this. However, I couldn't replicate the exact workflow locally. Manually I created a programming exercise with manuel assessment. I have made a submission as a student. After the submission date is due, I have made an assessment using an instructor account. However, I couldn't find a way to override another instructors assessment, since no assessments is shown on the dashboard. Is the issue about complaint mechanism or the regular assessment? Could you maybe provide some screenshots for me to understand better? Thanks in advance! :)

**Comment by b-fein** [comment]
As instructor, you need to go to the details page of the exercise and from there to the Scores page (button in the middle row for me, UI recently changed but should still be somewhere in this button-cluster):
![image](https://github.com/ls1intum/Artemis/assets/64250573/d6525c70-47ce-443e-9719-77d43d3db4d3)

In the list on the scores page you should now have the ‘Open Assessment’ option on the right:
![image](https://github.com/ls1intum/Artemis/assets/64250573/6f00a553-2620-4e1d-855d-8b936adee6ae)

This opens the regular assessment view and you can add additional feedback and override the assessment.
