### ISSUE TITLE
User management: re-add filter for users not in any course

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#8256]
### Is your feature request related to a problem?

It was possible in the past to filter for the list of users not in a any course in the admin user management view. This is quite important for us for data protection reasons to remove users no longer associated with any course.

With the Spring 3 upgrade the corresponding server implementation was also removed:

> Removed support for filtering by courses when retrieving users. We didn't use it in the client and it caused issues during the upgrade process.

### Describe the solution you'd like

I would like to be able to filter for users not associated with any course again to then be able to bulk-delete them in Artemis and connected systems.

### Describe alternatives you've considered

None, legal reasons require the deletion of users no longer actively using Artemis.

### Additional context

/cc @dfuchss Since I think you have used this feature in the past as well.

Related issues #5061, #6102

**Comment by dfuchss** [comment]
Yes, highly important for us as well.

**Comment by julian-christl** [comment]
I'll add this feature back. That's no issue. We can't maintain filtering users by specific courses via the main user endpoint.
As this is not a production issue, I'll close the issue. I'll shortly update the 3.x upgrade PR with a fix for this and notify you there.

**Comment by b-fein** [comment]
Looks like it has been removed in #7826

**Comment by julian-christl** [comment]
Oh, you need a full client-side implementation. I assumed you only referred to the API endpoint. Then let's keep it open. I'll readd the endpoint either way.

**Comment by krusche** [comment]
I intentionally removed the feature in https://github.com/ls1intum/Artemis/pull/7826, because it was not working correctly (in particular the UI was awful when there were more than 20 courses) and way too much data was sent between client and server. I suggest that we implement the feature in a correct and meaningful way. In particular, it was possible to select single courses, which apparently is not needed as feature. So a minimal implementation would be to filter for users that are not in any course. This might be easy to implement.

**Comment by julian-christl** [comment]
Would it make sense to simply implement that feature on it's own?
So, unless you need a two-step confirmation (loading users and looking at them and then confirmation for deletion), we could simply introduce a button in the user administration that calls an endpoint that just deletes all users that are not in a course

**Comment by krusche** [comment]
I would keep a confirmation dialog. In fact, we should even extend it and display all users that would be deleted, to make sure nothing problematic happens.

**Comment by BaumiCoder** [comment]
The approach with a confirmation dialog raises a few questions for me: The dialog should contain a list of all the users, which should be deleted. Which attributes of the users are necessary to display there? There can be quite a lot of such users, so this list needs pagination, right?

Wouldn't it be easier to extend the existing filter of the user-management? There we already have a user list with many feature like (all) attributes and pagination. It only needs to be a filter `Enrolled` with options `Yes` and `No`, with `Enrolled in at least one course` as the hint at the question mark. A filter instead of an extra button for this purpose would be also more powerful. You could also combine it with other filters or select all users after the filter is applied, but deselect some special users, which you don't want to delete, before hitting the `Delete` button.

**Comment by BaumiCoder** [comment]
@krusche @julian-christl What to you think about my approach to extend the filter options? If you are fine with this approach, I could overtake the implementation of it.

**Comment by krusche** [comment]
Delete is a destructive option which cannot be undone, therefore it's always important to be clear about what is deleted. If you really want to delete many users the confirmation dialog could something like:

This action will the following 203 users. Are you sure? This destructive action can **NOT** be undone:

Users, UserB, UserC, ...

The dialog would offer scrolling if it has too many lines.

There is no need for pagination here, because this is rarely used and therefore won't lead to any issues as we most likely will never delete more than 5000 users.

The actual filtering will be done on the "normal" view.

PS: please ping me on Slack if you have questions. I do not review all GitHub notifications, because I get too many

**Comment by BaumiCoder** [comment]
A simple listing of logins for the confirmation dialog is a good idea. I will implement it in this way.

However, I found an issue with the filtering in the "normal" view of the user management. The checkbox `All` only refers to the current page in the pagination of the data. This implies that deleting more users than 50 would need more user interactions (50 users per page). So I will add an button `delete not enrolled users` which also does the filtering. This will allow to easily delete higher number of user (50+) too.
