### ISSUE TITLE
Improve presentation score

### ISSUE THREAD

**Issue by lovaiible** [ls1intum/Artemis#865]
### Describe the solution you'd like
1. The presentation score should not be available to quizzes

2. During create / edit course, the feature can be activated / deactivated. The score is only shown in the course overview statistics if the feature is active

3. If the feature is active for a course, an instructor should be able to configure during create/edit exercise (for all types except quizzes) if the presentation score is used or not. Default is that it is not used. If the presentation score is not used in an exercise, then the buttons in the participation list are now shown and they can also not be added on the respective endpoint.

**Comment by krusche** [comment]
Thanks for creating this issue.

One additional comment to 2:
After activating the feature in the create / edit course dialog. The instructor can define how many presentations the students need to reach the bonus, e.g. 2. We can then simply store this number in the database. It the value is null (0 or for any reason negative), the feature is deactivated. If it is positive, the feature is activated. In the UI, it should still be shown to the instructor as checkbox, so that it is clear the feature has to be activated. If the instructor activates the feature, he has to enter a positive number. If the instructor deactivates the feature, the text box is disabled and after save, the value in the db is set to null.
