### ISSUE TITLE
Group and Sort Exercises in Course Dashboard

### ISSUE THREAD

**Issue by krusche** [ls1intum/ArTEMiS#88]
Allow users to group the exercises according to:
- Exercise Type
- Release Date
- Due Date (standard)

For Release Date and Due Date, it should be displayed on a weekly basis

**Comment by krusche** [comment]
implemented by @maximilianmeier

**Comment by Khalphion** [comment]
Currently, exercises are grouped by type. However, I think an option to switch to a time-linear view would also be handy in some cases; maybe add an option to switch views where all exercises are ordered by release date/due date and grouped by week instead of their types? 

![image](https://user-images.githubusercontent.com/10117554/56887277-7fd49e00-6a71-11e9-825e-e60608e694dd.png)

**Comment by Khalphion** [comment]
@krusche There are still a lot of places where ordering is not implemented. It's getting really inconvenient to find an exercise, e.g. the default sorting by exercise type in the tutor dashboard is absolutely useless. Also as a user, I don't understand why H**02**E01..., H**01**E**02**, H01E**03**, H01E**04**, H01E**01** is a meaningful order.

Please fix this, it shouldn't be something hard to do but helps a lot for everyday users like tutors.

![Screenshot from 2019-05-30 23-23-20](https://user-images.githubusercontent.com/10117554/58665848-137be180-8332-11e9-870a-4d19a9c863ea.png)

**Comment by krusche** [comment]
@Khalphion we will fix the order in the tutor course dashboard and also make sure the option show finished exercises works
