### ISSUE TITLE
Let Authentication support bearer

### ISSUE THREAD

**Issue by janthoXO** [ls1intum/Artemis#8817]
### Is your feature request related to a problem?

Not every client can use cookies. Therefore an option to authenticate without cookies should be possible

### Describe the solution you'd like

An endpoint similar to the standard authentication endpoint, but that the token is returned in the body.
In addition, rekeying is needed for the plugin use in Theia so that the user does not have to authenticate more than once.

**Comment by krusche** [comment]
We intentionally decided to use cookies after long discussions about usability and security concerns. Before we implement and merge changes, I would like to discuss such issues, because this can have many implications.

I also would need more information about clients that cannot use cookies for the discussion.
