### ISSUE TITLE
`Modeling`: The solution edit and view in component diagrams show two different diagrams 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#8823]
### Describe the bug

The solution (edit) shows good the lollipop and sockets but the view in the exercise does not show it correctly 

### To Reproduce

1. Create a component diagram 
2. Create the solution
3. Check that all is good in the edition
4. Save it and verify that it is not possible to distinguish the lollipops and sockets. 
5. And also out of the box view 

### Expected behavior

Should show the correct diagram 

### Screenshots

Edit view 
<img width="871" alt="image" src="https://github.com/ls1intum/Artemis/assets/88991954/a61673db-0a92-499d-bb56-482ea7ee7801">

Final view 

<img width="1025" alt="image" src="https://github.com/ls1intum/Artemis/assets/88991954/9e6ee69a-2c11-4a57-ad38-dd9ae7506b94">

### Which version of Artemis are you seeing the problem on?

7.2.2

### What browsers are you seeing the problem on?

Chrome

**Comment by loreanvictor** [comment]
@Santia-go could you provide the full diagram that is causing this issue? are you experiencing this issue with any component diagram?

**Comment by Santia-go** [comment]
> @Santia-go could you provide the full diagram that is causing this issue? are you experiencing this issue with any component diagram?

Any diagram. Also, when the students see the summary in the Exam mode, it is impossible to distinguish sockets and lollipops.

**Comment by loreanvictor** [comment]
ok this looks like a weird SVG rendering issue on Chrome and Firefox. Safari displays the diagrams properly:

<img width="989" alt="Screenshot 2024-07-12 at 14 26 25" src="https://github.com/user-attachments/assets/88bba7ca-8b0f-4fd1-8a63-b4255ca9f36d">

The same exercise looks like this on Chrome:

<img width="989" alt="Screenshot 2024-07-12 at 14 25 30" src="https://github.com/user-attachments/assets/28531e1a-8e2a-47df-9232-69f965a19b65">

and on Firefox:

<img width="989" alt="Screenshot 2024-07-12 at 14 25 07" src="https://github.com/user-attachments/assets/26cb9a20-a751-4ada-99e3-1490e71de3ba">

When I copy the content of the SVG element rendered and save it locally, it renders properly. [SVGViewer](https://www.svgviewer.dev) also renders the SVG properly on all browsers.

---

A potential solution for Chrome and Firefox seems to be using an HTML image element to render the SVG, instead of rendering it directly (using an SVG element), at least as per my initial testing. Right now we are inserting the SVG using [inner HTML](https://github.com/ls1intum/Artemis/blob/54f96250ab758e5dc9366d5b5882fed456172fed/src/main/webapp/app/exercises/modeling/shared/modeling-editor.component.html#L111), looking schematically like this:

```html
<div [innerHTML]="readOnlySVG" ...>
```

But I suspect doing this (schematically) instead, would fix the issue for Chrome and Firefox:

```html
<div ...>
  <img [src]="'data:image/svg+xml,' + encodeURIComponent(readOnlySVG)" />
</div>
```

Unfortunately, this fix would break the rendering on Safari (resulting in the same issue we have right now with Chrome and Firefox). So the fix potentially should check the browser and use the rendering technique accordingly.

P.S. I've tested this solution using console only (creating an image element and setting its source to the prescribed URI). I doubt there will be weird interactions with Angular, but since the solution is finicky extra testing would be a good idea.

**Comment by FelixTJDietrich** [comment]
The issue is with the ids of the marker elements of the SVG. There is a hidden Apollon editor in the DOM rendering the SVG a first time and then there is a second one the "readOnly" SVG. Both are using the same content. The duplicate `<marker>` ids on the page are causing issues for the second SVG and any subsequent ones. 

I thought about using the `useId()` hook on the Apollon side in an attempt to get more unique ids but I think that might also be the wrong approach. They could still collide.

What I did now is to destroy the `ApollonEditor` after `exportAsSVG` in `modeling-editor.component.ts`. I will create a pull request and link it here. This would solve the current issue but it would not solve it in potential future cases where the exact same Apollon SVG diagram appears more than once on the page.
