### ISSUE TITLE
Learning path exercises order keeps changing: See PR #9565

### ISSUE THREAD

**Issue by HawKhiem** [ls1intum/Artemis#9581]
### Describe the bug

The order of two exercises in a learning path changes as I go through them

https://github.com/user-attachments/assets/2c7d59c0-ac72-4f1a-b165-be7fc70162d3

### To Reproduce

1. Go to 'https://artemis-test5.artemis.cit.tum.de/courses/30/learning-path'
2. Click on 'Next' till the end of the learning path then click on Previous
3. The order of the exercises change from test1 -> test2 -> end of learning path to test2 -> test1 -> end of learning path. These two orders alternate

### Expected behavior

I presume the order should not change! I haven't tested with more exercises, but that might reduce the usability.

### Which version of Artemis are you seeing the problem on?

7.6.3

### What browsers are you seeing the problem on?

Chrome

### Additional context

This should be reproducible independent of PR #9565

**Comment by JohannesStoehr** [comment]
The order of learning objects will be fixed in #9565.
Regarding the issue that the next and previous learning object is the same, this is ok, since this learning object is part of multiple competencies. When progressing to the next learning object, the competency is also tracked, so there cannot be any loops in the learning path
