### ISSUE TITLE
Properly handle multiple submissions with the same commit hash

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#970]
We have a couple of students experiencing the issue that their submission is not retrieved properly in Artemis due to the following exception

Oct 21 21:09:49 vmbruegge106 artemis.sh[22805]: java.lang.IllegalStateException: Submission for participation id 192278 and commitHash ef91dd70d8aa91bab37cab1d4ac3277042f699b2 already exists!
Oct 21 21:09:49 vmbruegge106 artemis.sh[22805]:         at de.tum.in.www1.artemis.service.ProgrammingSubmissionService.notifyPush(ProgrammingSubmissionService.java:128)

I don't really understand how this issue can happen, but it might negatively affect students, so we should investigate why this can be the case.

**Comment by thilo-behnke** [comment]
From our investigation: This issue arises when the student uses branches; a commit to a branch can have the same commitHash as on master (= same commit), which triggers the creation of a submission in Artemis. Because we don't build branches beside master on Bamboo, no result will come in. This causes 'failed submissions' to be created.

**Comment by krusche** [comment]
we filter out all branches except master since some time so the issue does not happen any more
