### ISSUE TITLE
Exercise filter "Hide full score" not working correctly

### ISSUE THREAD

**Issue by max-ae** [ls1intum/Artemis#990]
### Describe the bug
See attached screenshots.
There are 4 exercises in total, 3 of them with 100% score. However, "Hide full score" only hides 1 of them.

#### To Reproduce

1. Go to 'Exercises' in a course with exercises with full score
2. Click on 'Hide full score'
3. See error

#### Expected behavior
All courses with full score are hidden.

#### Screenshots
![Bildschirmfoto 2019-10-26 um 23 20 47](https://user-images.githubusercontent.com/4730112/67626148-9d7b9800-f847-11e9-8de5-6e65f1914452.png)
![Bildschirmfoto 2019-10-26 um 23 20 54](https://user-images.githubusercontent.com/4730112/67626149-9fddf200-f847-11e9-95b1-9909d1754155.png)

### Environment

<details><pre>
 - OS: macOS 10.15
 - Browser Safari
 - Version 13.0.2
</pre></details>

**Comment by krusche** [comment]
@ungaralex what is the status of this issue?

**Comment by madwau** [comment]
I looked into this. The bug occurs when there are multiple results for a participation and the latest one has a full score while one of the previous results does not (the "full score" predicate right now falsely requires that all of the results have a full score instead of just the latest one). It only occurs when some of the results were sent via websockets (otherwise there is only one result that comes from the server). I'll create an MR for this and adapt the logic in the "full score" predicate.
