### ISSUE TITLE
Score not consistent with exercise results

### ISSUE THREAD

**Issue by lgerhardt45** [ls1intum/Artemis#995]
### Describe the bug
The exercise's score and grading status aren't updated (after automated tests ran past-deadline)

#### To Reproduce
1. Go to an exercise which had "hidden tests" (PGdP case past-deadline) run 
2. Click on `Show all results`
3. Compare the most recent grading result with the score label in the top right/ on the _Exercise_ tab on the course page

#### Expected behavior
Consistent visualisation/ labeling of my score

#### Screenshots
![Aufgabe Woche 01 H 01 on course page - Artemis](https://user-images.githubusercontent.com/40395744/67675228-ebdf8280-f97e-11e9-90cf-71879e660c79.png)
![Aufgabe Woche 01 H 01 - Artemis](https://user-images.githubusercontent.com/40395744/67675229-ebdf8280-f97e-11e9-90fd-f4438cca6071.png)

### Environment

<details><pre>
 - OS: MacOS 10.15
 - Browser: Chrome
 - Version 77.0.3865.120 (Official Build) (64-bit)
</pre></details>

#### Additional context
This happened today (Monday, 28.10.2019) in the PGdP course, where "additional" tests are run after the deadline past.

**Comment by krusche** [comment]
@ungaralex @thilo-behnke could you please look into this? Thanks

**Comment by thilo-behnke** [comment]
The result that was generated by the automatic build run has the attribute `graded = false` because the result was generated after the due date. TBD if this makes sense, @krusche and I discussed recently if this needs to be 'inverted'.
The updating-result component that is shown at the top right, by default filters ungraded results, while the result history and the result component in the code-editor does not.

**Comment by thilo-behnke** [comment]
I looked into the code more deeply, my last comment is partly incorrect: We have a special case for submissions with the type 'INSTRUCTOR', they are always graded, regardless of the due date.
So if the result was generated by the automatic build run, the question is why it is ungraded.

The only way this can be the case, is if the submission could not be found when the result is sent from the CIS (in this case a submission is created with type OTHER).
The only workaround is to manually trigger the builds of concerned student results in scores.

After discussing this internally we assume that there is an issue with the communication between Artemis, Bamboo, Bitbucket because of the high amount of simultaneous REST calls: https://github.com/ls1intum/Artemis/issues/1000.

**Comment by jerhard** [comment]
Regarding how the grading status should be updated: The status `graded` probably should only appear when all planned assessment steps are done. I.e. in case of an exercise with both tests after the deadline and a tutor assessment, `graded` should only appear when a tutor gave an assessment.
