### ISSUE TITLE
Missing pagination for scores page

### ISSUE THREAD

**Issue by michaelspiss** [ls1intum/Artemis#999]
### Describe the bug
The "scores" page slows down significantly or crashes the browser if there are many participants. Often times there are paint errors as well (e.g. scroll bar is at full length and just goes off-screen once used, the page is just grey after scrolling down 15 list items, footer is in the middle of the screen, etc.) .
Sorting by a criteria like "login" or just searching for a value with the browser's built in "find in page" becomes impossible (crash or stuck for >10 minutes). Some also reported 100% cpu usage, which consequently slows down the whole pc and makes grading the submissions very hard to do.

#### To Reproduce
Open the "scores" page of an exercise with >1500 participants.

#### Expected behavior
The page should not load all participants at once, but rather 50 (or even 100) with pagination. Sorting by name or any other criteria must still work.

### Environment

<details><pre>
 - OS: every
 - Browser: tested in firefox, edge, chrome
</pre></details>

**Comment by thilo-behnke** [comment]
Thanks for the report.
The issue here is that we are using a plain HTML table without any visualization / lazy loading / pagination functionality. This causes all elements in the table to be rendered at once which leads to the described high memory / cpu usage.

The idea would be to migrate the table to http://swimlane.github.io/ngx-datatable/ (already a dependency of Artemis).

**Comment by krusche** [comment]
Thanks for reporting this. We will improve this in the future as @thilo-behnke mentioned. 

In the mean time, please use Google Chrome which does a fairly good job in rendering this page, even for >1500 results. I just tried it for the exercise in PGdP with 1656 results and for me it only takes a few seconds until the page is loaded. Scrolling and sorting works fine and I don't see any rendering issues. Sorting and filtering only takes around 1-2s, so the performance is ok to work with the page.

**Comment by michaelspiss** [comment]
Thank you! I sadly cannot confirm your observation on my machine. It takes several (>5) minutes for the page to build and allow interaction (like "download repos"), even with a fresh installation of chrome.

**Comment by Garfield96** [comment]
Although pagination might be useful for some users, which suffer from slow browsers or internet connection, it is not useful for others. Personally, the fact that all information is available at once is one of the great features of Artemis. Searching for a participant using Ctrl+F is extremely fast (at least on my machine) and wouldn't be possible with pagination. Besides, now I can scroll through the results to get a rough estimation of whether students have problems with the task or not. I don't want to click through 10 pages to do that. 
To make everyone happy, I would suggest adding user preferences which determine whether pagination is used or not.

**Comment by krusche** [comment]
@Garfield96 I agree :) and we are currently discussing how to implement this in the right way with customization in mind. This makes it a bit more time consuming to implement pagination, but I think it's worth spending the effort to make everyone happy ;)

**Comment by Isigiel** [comment]
Even on a fast machine I see my browser struggling hard with this.
What @thilo-behnke mentionaed seems like a good way to go, use the ngx-datatable for it's vitual scrolling and implement the search functionality in the app.
Users should not be forced to use the browser search in page option. This would also fix both problems mentioned by @Garfield96 , scrolling through results is still possible and the search will be offered by artemis, ngx-datatable seems to have a filtering feature that should work just fine.

**Comment by krusche** [comment]
We tried out ngx-datatable and did not see huge performance improvements without pagination, so we are not sure if the virtual scrolling really solves all problems here.

Ideally the pagination and search happens on the server side (if the user wants this), because then we also avoid that all the data needs to be loaded.

We will further investigate this issue

**Comment by 13XxM1CHA3lxX37** [comment]
I think that's a Browser/Configuration issue. Tried to reproduce it to no avail and I also agree with @Garfield96 it's handy to see everything at once

Config: macOS Mojave, Late 2013 15" MB Pro, 16GB RAM, NVME SSD
- 10-30s in Chrome (keep in mind that I have over 50 additional open tabs)
- 20s with Chrome in a Win7 Virtual Machine
- 10s in Safari
- 15s in Firefox
- 15s in TOR Browser (so it seems to not be affected by internet speed)

Config: Win10, i7 4710HQ (2014), 16GB RAM, SATA SSD
- 30s in MS Edge
- 15s in Chrome

**Comment by krusche** [comment]
@13XxM1CHA3lxX37 thanks for these numbers. How many results/students did you have in your tests?

What I recognized as well in the Chrome developer tools: the download of the data from the server only takes 1-2s for ~1650 students/results. So getting the data is not a real problem. The problem is the rendering part and probably also the change detection of Angular. Maybe we can tweak something here as well

**Comment by 13XxM1CHA3lxX37** [comment]
@krusche Tested everything with 1656 results from the PGdP W01 H01 exercise

**Comment by krusche** [comment]
We improved the page. Please try it out and let us know if it works better for you!

It still has some minor issues, but we wanted to deploy it to improve the situation. If you change the results per page to a large number, it can take a while, the rendering is not animated. However the browser remembers your preference and the next time you open this page the same result per page limit will be used as the last time. 

Resizing the browser window can lead to issues as well and the footer might not perfectly be aligned.

**Comment by Garfield96** [comment]
I tested the new page a little bit and found the following issues:
- I like the preview of search results while typing a student id. Unfortunately, if the preview list is very long it gets cut off at the end of the screen. To avoid this problem, the length of the preview list should be limited to the screen height and if there are more entries, the list should be scrollable (without scrolling the whole page)
- I don't think that it is reasonable to have a setting to show 2000 students per page. I would recommend to replace this option by "all"
- Many students have multiple given names but use only one of them. If I try to find a student by only entering the first given name and surname, the student is not shown when he/she has a second given name.
- Sorting is not working or takes extremely long (number of students per page does not influence that)
- To improve the performance of sorting, it would be nice when the sorting is only done by the server if not all scores are shown. If all scores are shown, then the sorting should be done on the client-side (like before)
- The feature set and look should be equal for all lists in Artemis. Therefore, the participation listing should be changed as well.
- Occasionally, some rows show a significant offset, which makes the list almost unreadable 
- Nice to have: wildcard support in search strings

Due to data protection laws, I cannot post screenshots of these effects. If those are needed, I could send screenshots via email.

#### Environment
 - OS: Debian Buster
 - Browser: Mozilla Firefox
 - Version: 68.2.0esr (64-bit)

**Comment by krusche** [comment]
Thanks for reporting these issues. Apart from those: is the page working for you at the moment without significant problems? So can you live with the current state for the next couple of days? 😉

**Comment by Garfield96** [comment]
> Thanks for reporting these issues. Apart from those: is the page working for you at the moment without significant problems? So can you live with the current state for the next couple of days? 

In my opinion, there are no urgent problems.
